---
title: "Georgia Medicaid Work Requirements"
output: html_document
date: "2025-03-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load libraries

```{r libraries}
library(tidyverse)
library(haven)
library(summarytools)
library(survey)
library(srvyr)
library(zoo)
```

## Load data

```{r}
puf_41 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week41_PUF_CSV/pulse2022_puf_41.csv")
puf_42 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week42_PUF_CSV/pulse2022_puf_42.csv")
puf_43 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week43_PUF_CSV/pulse2022_puf_43.csv")
puf_44 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week44_PUF_CSV/pulse2022_puf_44.csv")
puf_45 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week45_PUF_CSV/pulse2022_puf_45.csv")
puf_46 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week46_PUF_CSV/pulse2022_puf_46.csv")
puf_47 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week47_PUF_CSV/pulse2022_puf_47.csv")
puf_48 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week48_PUF_CSV/pulse2022_puf_48.csv")
puf_49 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week49_PUF_CSV/pulse2022_puf_49.csv")
puf_50 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week50_PUF_CSV/pulse2022_puf_50.csv")
puf_51 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week51_PUF_CSV/pulse2022_puf_51.csv")
puf_52 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week52_PUF_CSV/pulse2022_puf_52.csv")
puf_53 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week53_PUF_CSV/pulse2023_puf_53.csv")
puf_54 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week54_PUF_CSV/pulse2023_puf_54.csv")
puf_55 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week55_PUF_CSV/pulse2023_puf_55.csv")
puf_56 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week56_PUF_CSV/pulse2023_puf_56.csv")
puf_57 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week57_PUF_CSV/pulse2023_puf_57.csv")
puf_58 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week58_PUF_CSV/pulse2023_puf_58.csv")
puf_59 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week59_PUF_CSV/pulse2023_puf_59.csv")
puf_60 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week60_PUF_CSV/pulse2023_puf_60.csv")
puf_61 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week61_PUF_CSV/pulse2023_puf_61.csv")
puf_62 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week62_PUF_CSV/pulse2023_puf_62.csv")
puf_63 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week63_PUF_CSV/pulse2023_puf_63.csv")
puf_401 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Phase4Cycle01_PUF_CSV/hps_04_00_01_puf.csv")
puf_402 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Phase4Cycle02_PUF_CSV/hps_04_00_02_puf.csv")
puf_403 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Phase4Cycle03_PUF_CSV/hps_04_00_03_puf.csv")
puf_404 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Phase4-1Cycle04_PUF_CSV/hps_04_01_04_puf.csv")
puf_405 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Phase4-1Cycle05_PUF_CSV/hps_04_01_05_puf.csv")
puf_406 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Phase4-1Cycle06_PUF_CSV/hps_04_01_06_puf.csv")
puf_407 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Phase4-1Cycle07_PUF_CSV/hps_04_01_07_puf.csv")
puf_408 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Phase4-2Cycle08_PUF_CSV/hps_04_02_08_puf.csv")
puf_409 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Phase4-2Cycle09_PUF_CSV/hps_04_02_09_puf.csv")
```

# Select variables
```{r}
puf_41 <- puf_41 %>% select("TBIRTH_YEAR", "RHISPANIC", "RRACE", "EEDUC", "EGENID_BIRTH", "THHLD_NUMPER", "ANYWORK", "HLTHINS1", "HLTHINS2", "HLTHINS3", "HLTHINS4", "HLTHINS5", "HLTHINS6", "HLTHINS7", "HLTHINS8", "INCOME", "EST_ST", "PWEIGHT", "HWEIGHT", "SCRAM", "WEEK")
puf_42 <- puf_42 %>% select("TBIRTH_YEAR", "RHISPANIC", "RRACE", "EEDUC", "EGENID_BIRTH", "THHLD_NUMPER", "ANYWORK", "HLTHINS1", "HLTHINS2", "HLTHINS3", "HLTHINS4", "HLTHINS5", "HLTHINS6", "HLTHINS7", "HLTHINS8", "INCOME", "EST_ST", "PWEIGHT", "HWEIGHT", "SCRAM", "WEEK")
puf_43 <- puf_43 %>% select("TBIRTH_YEAR", "RHISPANIC", "RRACE", "EEDUC", "EGENID_BIRTH", "THHLD_NUMPER", "ANYWORK", "HLTHINS1", "HLTHINS2", "HLTHINS3", "HLTHINS4", "HLTHINS5", "HLTHINS6", "HLTHINS7", "HLTHINS8", "INCOME", "EST_ST", "PWEIGHT", "HWEIGHT", "SCRAM", "WEEK")
puf_44 <- puf_44 %>% select("TBIRTH_YEAR", "RHISPANIC", "RRACE", "EEDUC", "EGENID_BIRTH", "THHLD_NUMPER", "ANYWORK", "HLTHINS1", "HLTHINS2", "HLTHINS3", "HLTHINS4", "HLTHINS5", "HLTHINS6", "HLTHINS7", "HLTHINS8", "INCOME", "EST_ST", "PWEIGHT", "HWEIGHT", "SCRAM", "WEEK")
puf_45 <- puf_45 %>% select("TBIRTH_YEAR", "RHISPANIC", "RRACE", "EEDUC", "EGENID_BIRTH", "THHLD_NUMPER", "ANYWORK", "HLTHINS1", "HLTHINS2", "HLTHINS3", "HLTHINS4", "HLTHINS5", "HLTHINS6", "HLTHINS7", "HLTHINS8", "INCOME", "EST_ST", "PWEIGHT", "HWEIGHT", "SCRAM", "WEEK")
puf_46 <- puf_46 %>% select("TBIRTH_YEAR", "RHISPANIC", "RRACE", "EEDUC", "EGENID_BIRTH", "THHLD_NUMPER", "ANYWORK", "HLTHINS1", "HLTHINS2", "HLTHINS3", "HLTHINS4", "HLTHINS5", "HLTHINS6", "HLTHINS7", "HLTHINS8", "INCOME", "EST_ST", "PWEIGHT", "HWEIGHT", "SCRAM", "WEEK")
puf_47 <- puf_47 %>% select("TBIRTH_YEAR", "RHISPANIC", "RRACE", "EEDUC", "EGENID_BIRTH", "THHLD_NUMPER", "ANYWORK", "HLTHINS1", "HLTHINS2", "HLTHINS3", "HLTHINS4", "HLTHINS5", "HLTHINS6", "HLTHINS7", "HLTHINS8", "INCOME", "EST_ST", "PWEIGHT", "HWEIGHT", "SCRAM", "WEEK")
puf_48 <- puf_48 %>% select("TBIRTH_YEAR", "RHISPANIC", "RRACE", "EEDUC", "EGENID_BIRTH", "THHLD_NUMPER", "ANYWORK", "HLTHINS1", "HLTHINS2", "HLTHINS3", "HLTHINS4", "HLTHINS5", "HLTHINS6", "HLTHINS7", "HLTHINS8", "INCOME", "EST_ST", "PWEIGHT", "HWEIGHT", "SCRAM", "WEEK")
puf_49 <- puf_49 %>% select("TBIRTH_YEAR", "RHISPANIC", "RRACE", "EEDUC", "EGENID_BIRTH", "THHLD_NUMPER", "ANYWORK", "HLTHINS1", "HLTHINS2", "HLTHINS3", "HLTHINS4", "HLTHINS5", "HLTHINS6", "HLTHINS7", "HLTHINS8", "INCOME", "EST_ST", "PWEIGHT", "HWEIGHT", "SCRAM", "WEEK")
puf_50 <- puf_50 %>% select("TBIRTH_YEAR", "RHISPANIC", "RRACE", "EEDUC", "EGENID_BIRTH", "THHLD_NUMPER", "ANYWORK", "HLTHINS1", "HLTHINS2", "HLTHINS3", "HLTHINS4", "HLTHINS5", "HLTHINS6", "HLTHINS7", "HLTHINS8", "INCOME", "EST_ST", "PWEIGHT", "HWEIGHT", "SCRAM", "WEEK")
puf_51 <- puf_51 %>% select("TBIRTH_YEAR", "RHISPANIC", "RRACE", "EEDUC", "EGENID_BIRTH", "THHLD_NUMPER", "ANYWORK", "HLTHINS1", "HLTHINS2", "HLTHINS3", "HLTHINS4", "HLTHINS5", "HLTHINS6", "HLTHINS7", "HLTHINS8", "INCOME", "EST_ST", "PWEIGHT", "HWEIGHT", "SCRAM", "WEEK")
puf_52 <- puf_52 %>% select("TBIRTH_YEAR", "RHISPANIC", "RRACE", "EEDUC", "EGENID_BIRTH", "THHLD_NUMPER", "ANYWORK", "HLTHINS1", "HLTHINS2", "HLTHINS3", "HLTHINS4", "HLTHINS5", "HLTHINS6", "HLTHINS7", "HLTHINS8", "INCOME", "EST_ST", "PWEIGHT", "HWEIGHT", "SCRAM", "WEEK")
puf_53 <- puf_53 %>% select("TBIRTH_YEAR", "RHISPANIC", "RRACE", "EEDUC", "EGENID_BIRTH", "THHLD_NUMPER", "ANYWORK", "HLTHINS1", "HLTHINS2", "HLTHINS3", "HLTHINS4", "HLTHINS5", "HLTHINS6", "HLTHINS7", "HLTHINS8", "INCOME", "EST_ST", "PWEIGHT", "HWEIGHT", "SCRAM", "WEEK")
puf_54 <- puf_54 %>% select("TBIRTH_YEAR", "RHISPANIC", "RRACE", "EEDUC", "EGENID_BIRTH", "THHLD_NUMPER", "ANYWORK", "HLTHINS1", "HLTHINS2", "HLTHINS3", "HLTHINS4", "HLTHINS5", "HLTHINS6", "HLTHINS7", "HLTHINS8", "INCOME", "EST_ST", "PWEIGHT", "HWEIGHT", "SCRAM", "WEEK")
puf_55 <- puf_55 %>% select("TBIRTH_YEAR", "RHISPANIC", "RRACE", "EEDUC", "EGENID_BIRTH", "THHLD_NUMPER", "ANYWORK", "HLTHINS1", "HLTHINS2", "HLTHINS3", "HLTHINS4", "HLTHINS5", "HLTHINS6", "HLTHINS7", "HLTHINS8", "INCOME", "EST_ST", "PWEIGHT", "HWEIGHT", "SCRAM", "WEEK")
puf_56 <- puf_56 %>% select("TBIRTH_YEAR", "RHISPANIC", "RRACE", "EEDUC", "EGENID_BIRTH", "THHLD_NUMPER", "ANYWORK", "HLTHINS1", "HLTHINS2", "HLTHINS3", "HLTHINS4", "HLTHINS5", "HLTHINS6", "HLTHINS7", "HLTHINS8", "INCOME", "EST_ST", "PWEIGHT", "HWEIGHT", "SCRAM", "WEEK")
puf_57 <- puf_57 %>% select("TBIRTH_YEAR", "RHISPANIC", "RRACE", "EEDUC", "EGENID_BIRTH", "THHLD_NUMPER", "ANYWORK", "HLTHINS1", "HLTHINS2", "HLTHINS3", "HLTHINS4", "HLTHINS5", "HLTHINS6", "HLTHINS7", "HLTHINS8", "INCOME", "EST_ST", "PWEIGHT", "HWEIGHT", "SCRAM", "WEEK")
puf_58 <- puf_58 %>% select("TBIRTH_YEAR", "RHISPANIC", "RRACE", "EEDUC", "EGENID_BIRTH", "THHLD_NUMPER", "ANYWORK", "HLTHINS1", "HLTHINS2", "HLTHINS3", "HLTHINS4", "HLTHINS5", "HLTHINS6", "HLTHINS7", "HLTHINS8", "INCOME", "EST_ST", "PWEIGHT", "HWEIGHT", "SCRAM", "WEEK")
puf_59 <- puf_59 %>% select("TBIRTH_YEAR", "RHISPANIC", "RRACE", "EEDUC", "EGENID_BIRTH", "THHLD_NUMPER", "ANYWORK", "HLTHINS1", "HLTHINS2", "HLTHINS3", "HLTHINS4", "HLTHINS5", "HLTHINS6", "HLTHINS7", "HLTHINS8", "INCOME", "EST_ST", "PWEIGHT", "HWEIGHT", "SCRAM", "WEEK")
puf_60 <- puf_60 %>% select("TBIRTH_YEAR", "RHISPANIC", "RRACE", "EEDUC", "EGENID_BIRTH", "THHLD_NUMPER", "ANYWORK", "HLTHINS1", "HLTHINS2", "HLTHINS3", "HLTHINS4", "HLTHINS5", "HLTHINS6", "HLTHINS7", "HLTHINS8", "INCOME", "EST_ST", "PWEIGHT", "HWEIGHT", "SCRAM", "WEEK")
puf_61 <- puf_61 %>% select("TBIRTH_YEAR", "RHISPANIC", "RRACE", "EEDUC", "EGENID_BIRTH", "THHLD_NUMPER", "ANYWORK", "HLTHINS1", "HLTHINS2", "HLTHINS3", "HLTHINS4", "HLTHINS5", "HLTHINS6", "HLTHINS7", "HLTHINS8", "INCOME", "EST_ST", "PWEIGHT", "HWEIGHT", "SCRAM", "WEEK")
puf_62 <- puf_62 %>% select("TBIRTH_YEAR", "RHISPANIC", "RRACE", "EEDUC", "EGENID_BIRTH", "THHLD_NUMPER", "ANYWORK", "HLTHINS1", "HLTHINS2", "HLTHINS3", "HLTHINS4", "HLTHINS5", "HLTHINS6", "HLTHINS7", "HLTHINS8", "INCOME", "EST_ST", "PWEIGHT", "HWEIGHT", "SCRAM", "WEEK")
puf_63 <- puf_63 %>% select("TBIRTH_YEAR", "RHISPANIC", "RRACE", "EEDUC", "EGENID_BIRTH", "THHLD_NUMPER", "ANYWORK", "HLTHINS1", "HLTHINS2", "HLTHINS3", "HLTHINS4", "HLTHINS5", "HLTHINS6", "HLTHINS7", "HLTHINS8", "INCOME", "EST_ST", "PWEIGHT", "HWEIGHT", "SCRAM", "WEEK")
puf_401 <- puf_401 %>% select("TBIRTH_YEAR", "RHISPANIC", "RRACE", "EEDUC", "EGENID_BIRTH", "THHLD_NUMPER", "ANYWORK", "HLTHINS1", "HLTHINS2", "HLTHINS3", "HLTHINS4", "HLTHINS5", "HLTHINS6", "HLTHINS7", "HLTHINS8", "INCOME", "EST_ST", "PWEIGHT", "HWEIGHT", "SCRAM", "CYCLE")
puf_402 <- puf_402 %>% select("TBIRTH_YEAR", "RHISPANIC", "RRACE", "EEDUC", "EGENID_BIRTH", "THHLD_NUMPER", "ANYWORK", "HLTHINS1", "HLTHINS2", "HLTHINS3", "HLTHINS4", "HLTHINS5", "HLTHINS6", "HLTHINS7", "HLTHINS8", "INCOME", "EST_ST", "PWEIGHT", "HWEIGHT", "SCRAM", "CYCLE")
puf_403 <- puf_403 %>% select("TBIRTH_YEAR", "RHISPANIC", "RRACE", "EEDUC", "EGENID_BIRTH", "THHLD_NUMPER", "ANYWORK", "HLTHINS1", "HLTHINS2", "HLTHINS3", "HLTHINS4", "HLTHINS5", "HLTHINS6", "HLTHINS7", "HLTHINS8", "INCOME", "EST_ST", "PWEIGHT", "HWEIGHT", "SCRAM", "CYCLE")
puf_404 <- puf_404 %>% select("TBIRTH_YEAR", "RHISPANIC", "RRACE", "EEDUC", "EGENID_BIRTH", "THHLD_NUMPER", "ANYWORK", "HLTHINS1", "HLTHINS2", "HLTHINS3", "HLTHINS4", "HLTHINS5", "HLTHINS6", "HLTHINS7", "HLTHINS8", "INCOME", "EST_ST", "PWEIGHT", "HWEIGHT", "SCRAM", "CYCLE")
puf_405 <- puf_405 %>% select("TBIRTH_YEAR", "RHISPANIC", "RRACE", "EEDUC", "EGENID_BIRTH", "THHLD_NUMPER", "ANYWORK", "HLTHINS1", "HLTHINS2", "HLTHINS3", "HLTHINS4", "HLTHINS5", "HLTHINS6", "HLTHINS7", "HLTHINS8", "INCOME", "EST_ST", "PWEIGHT", "HWEIGHT", "SCRAM", "CYCLE")
puf_406 <- puf_406 %>% select("TBIRTH_YEAR", "RHISPANIC", "RRACE", "EEDUC", "EGENID_BIRTH", "THHLD_NUMPER", "ANYWORK", "HLTHINS1", "HLTHINS2", "HLTHINS3", "HLTHINS4", "HLTHINS5", "HLTHINS6", "HLTHINS7", "HLTHINS8", "INCOME", "EST_ST", "PWEIGHT", "HWEIGHT", "SCRAM", "CYCLE")
puf_407 <- puf_407 %>% select("TBIRTH_YEAR", "RHISPANIC", "RRACE", "EEDUC", "EGENID_BIRTH", "THHLD_NUMPER", "ANYWORK", "HLTHINS1", "HLTHINS2", "HLTHINS3", "HLTHINS4", "HLTHINS5", "HLTHINS6", "HLTHINS7", "HLTHINS8", "INCOME", "EST_ST", "PWEIGHT", "HWEIGHT", "SCRAM", "CYCLE")
puf_408 <- puf_408 %>% select("TBIRTH_YEAR", "RHISPANIC", "RRACE", "EEDUC", "EGENID_BIRTH", "THHLD_NUMPER", "ANYWORK", "HLTHINS1", "HLTHINS2", "HLTHINS3", "HLTHINS4", "HLTHINS5", "HLTHINS6", "HLTHINS7", "HLTHINS8", "INCOME", "EST_ST", "PWEIGHT", "HWEIGHT", "SCRAM", "CYCLE")
puf_409 <- puf_409 %>% select("TBIRTH_YEAR", "RHISPANIC", "RRACE", "EEDUC", "EGENID_BIRTH", "THHLD_NUMPER", "ANYWORK", "HLTHINS1", "HLTHINS2", "HLTHINS3", "HLTHINS4", "HLTHINS5", "HLTHINS6", "HLTHINS7", "HLTHINS8", "INCOME", "EST_ST", "PWEIGHT", "HWEIGHT", "SCRAM", "CYCLE")
```

# Merge data
```{r}
data <- bind_rows(puf_41, puf_42, puf_43, puf_44, puf_45, puf_46, puf_47, puf_48, puf_49, puf_50, puf_51, puf_52, puf_53, puf_54, puf_55, puf_56, puf_57, puf_58, puf_59, puf_60, puf_61, puf_62, puf_63, puf_401, puf_402, puf_403, puf_404, puf_405, puf_406, puf_407, puf_408, puf_409)

rm("puf_41", "puf_42", "puf_43", "puf_44", "puf_45", "puf_46", "puf_47", "puf_48", "puf_49", "puf_50", "puf_51", "puf_52", "puf_53", "puf_54", "puf_55", "puf_56", "puf_57", "puf_58", "puf_59", "puf_60", "puf_61", "puf_62", "puf_63", "puf_401", "puf_402", "puf_403", "puf_404", "puf_405", "puf_406", "puf_407", "puf_408", "puf_409")
```

# Load weights
```{r}
repwgt_puf_41 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week41_PUF_CSV/pulse2022_repwgt_puf_41.csv")
repwgt_puf_42 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week42_PUF_CSV/pulse2022_repwgt_puf_42.csv")
repwgt_puf_43 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week43_PUF_CSV/pulse2022_repwgt_puf_43.csv")
repwgt_puf_44 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week44_PUF_CSV/pulse2022_repwgt_puf_44.csv")
repwgt_puf_45 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week45_PUF_CSV/pulse2022_repwgt_puf_45.csv")
repwgt_puf_46 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week46_PUF_CSV/pulse2022_repwgt_puf_46.csv")
repwgt_puf_47 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week47_PUF_CSV/pulse2022_repwgt_puf_47.csv")
repwgt_puf_48 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week48_PUF_CSV/pulse2022_repwgt_puf_48.csv")
repwgt_puf_49 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week49_PUF_CSV/pulse2022_repwgt_puf_49.csv")
repwgt_puf_50 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week50_PUF_CSV/pulse2022_repwgt_puf_50.csv")
repwgt_puf_51 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week51_PUF_CSV/pulse2022_repwgt_puf_51.csv")
repwgt_puf_52 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week52_PUF_CSV/pulse2022_repwgt_puf_52.csv")
repwgt_puf_53 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week53_PUF_CSV/pulse2023_repwgt_puf_53.csv")
repwgt_puf_54 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week54_PUF_CSV/pulse2023_repwgt_puf_54.csv")
repwgt_puf_55 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week55_PUF_CSV/pulse2023_repwgt_puf_55.csv")
repwgt_puf_56 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week56_PUF_CSV/pulse2023_repwgt_puf_56.csv")
repwgt_puf_57 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week57_PUF_CSV/pulse2023_repwgt_puf_57.csv")
repwgt_puf_58 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week58_PUF_CSV/pulse2023_repwgt_puf_58.csv")
repwgt_puf_59 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week59_PUF_CSV/pulse2023_repwgt_puf_59.csv")
repwgt_puf_60 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week60_PUF_CSV/pulse2023_repwgt_puf_60.csv")
repwgt_puf_61 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week61_PUF_CSV/pulse2023_repwgt_puf_61.csv")
repwgt_puf_62 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week62_PUF_CSV/pulse2023_repwgt_puf_62.csv")
repwgt_puf_63 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Week63_PUF_CSV/pulse2023_repwgt_puf_63.csv")
repwgt_puf_401 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Phase4Cycle01_PUF_CSV/hps_04_00_01_repwgt_puf.csv")
repwgt_puf_402 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Phase4Cycle02_PUF_CSV/hps_04_00_02_repwgt_puf.csv")
repwgt_puf_403 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Phase4Cycle03_PUF_CSV/hps_04_00_03_repwgt_puf.csv")
repwgt_puf_404 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Phase4-1Cycle04_PUF_CSV/hps_04_01_04_repwgt_puf.csv")
repwgt_puf_405 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Phase4-1Cycle05_PUF_CSV/hps_04_01_05_repwgt_puf.csv")
repwgt_puf_406 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Phase4-1Cycle06_PUF_CSV/hps_04_01_06_repwgt_puf.csv")
repwgt_puf_407 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Phase4-1Cycle07_PUF_CSV/hps_04_01_07_repwgt_puf.csv")
repwgt_puf_408 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Phase4-2Cycle08_PUF_CSV/hps_04_02_08_repwgt_puf.csv")
repwgt_puf_409 <- read_csv("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/Pulse/HPS_Phase4-2Cycle09_PUF_CSV/hps_04_02_09_repwgt_puf.csv")
```

# Merge weights and data
```{r}
weights <- bind_rows(repwgt_puf_41, repwgt_puf_42, repwgt_puf_43, repwgt_puf_44, repwgt_puf_45, repwgt_puf_46, repwgt_puf_47, repwgt_puf_48, repwgt_puf_49, repwgt_puf_50, repwgt_puf_51, repwgt_puf_52, repwgt_puf_53, repwgt_puf_54, repwgt_puf_55, repwgt_puf_56, repwgt_puf_57, repwgt_puf_58, repwgt_puf_59, repwgt_puf_60, repwgt_puf_61, repwgt_puf_62, repwgt_puf_63, repwgt_puf_401, repwgt_puf_402, repwgt_puf_403, repwgt_puf_404, repwgt_puf_405, repwgt_puf_406, repwgt_puf_407, repwgt_puf_408, repwgt_puf_409)

rm("repwgt_puf_41", "repwgt_puf_42", "repwgt_puf_43", "repwgt_puf_44", "repwgt_puf_45", "repwgt_puf_46", "repwgt_puf_47", "repwgt_puf_48", "repwgt_puf_49", "repwgt_puf_50", "repwgt_puf_51", "repwgt_puf_52", "repwgt_puf_53", "repwgt_puf_54", "repwgt_puf_55", "repwgt_puf_56", "repwgt_puf_57", "repwgt_puf_58", "repwgt_puf_59", "repwgt_puf_60", "repwgt_puf_61", "repwgt_puf_62", "repwgt_puf_63", "repwgt_puf_401", "repwgt_puf_402", "repwgt_puf_403", "repwgt_puf_404", "repwgt_puf_405", "repwgt_puf_406", "repwgt_puf_407", "repwgt_puf_408", "repwgt_puf_409")

data <- data %>% left_join(weights, by = c("SCRAM", "WEEK", "CYCLE"))

rm("weights")
```

# Clean data
```{r}
# Divide PWEIGHT by number of cycles
data$PWEIGHT_divided <- data$PWEIGHT/32

# Also Divide Replicate PWEIGHT by number of cycles
rep_cols <- grep("^PWEIGHT[0-9]+$", names(data), value = TRUE)
for (col in rep_cols) {
  data[[col]] <- data[[col]] / 32
}

# Clean time and state
data <- data %>%
  mutate(
    week_cycle = case_when(
      !is.na(WEEK) ~ WEEK,
      !is.na(CYCLE) ~ CYCLE + 63,
      TRUE ~ NA_real_
    ),
    date = case_when( # End date of each cycle
      WEEK == 41 ~ as.Date("2022-01-10"),
      WEEK == 42 ~ as.Date("2022-02-07"),
      WEEK == 43 ~ as.Date("2022-03-14"),
      WEEK == 44 ~ as.Date("2022-04-11"),
      WEEK == 45 ~ as.Date("2022-05-09"),
      WEEK == 46 ~ as.Date("2022-06-13"),
      WEEK == 47 ~ as.Date("2022-07-11"),
      WEEK == 48 ~ as.Date("2022-08-08"),
      WEEK == 49 ~ as.Date("2022-09-28"),
      WEEK == 50 ~ as.Date("2022-10-17"),
      WEEK == 51 ~ as.Date("2022-11-14"),
      WEEK == 52 ~ as.Date("2022-12-19"),
      WEEK == 53 ~ as.Date("2023-01-16"),
      WEEK == 54 ~ as.Date("2023-02-13"),
      WEEK == 55 ~ as.Date("2023-03-13"),
      WEEK == 56 ~ as.Date("2023-04-10"),
      WEEK == 57 ~ as.Date("2023-05-08"),
      WEEK == 58 ~ as.Date("2023-06-19"),
      WEEK == 59 ~ as.Date("2023-07-10"),
      WEEK == 60 ~ as.Date("2023-08-07"),
      WEEK == 61 ~ as.Date("2023-09-04"),
      WEEK == 62 ~ as.Date("2023-10-02"),
      WEEK == 63 ~ as.Date("2023-10-30"),
      CYCLE == 1 ~ as.Date("2024-02-05"),
      CYCLE == 2 ~ as.Date("2024-03-04"),
      CYCLE == 3 ~ as.Date("2024-04-01"),
      CYCLE == 4 ~ as.Date("2024-04-29"),
      CYCLE == 5 ~ as.Date("2024-05-27"),
      CYCLE == 6 ~ as.Date("2024-06-24"),
      CYCLE == 7 ~ as.Date("2024-07-22"),
      CYCLE == 8 ~ as.Date("2024-08-19"),
      CYCLE == 9 ~ as.Date("2024-09-16"),
      TRUE ~ NA_Date_
    ),
    year = year(date),
    month = month(date),
    quarter = as.yearqtr(date),
    quarter_factor = factor(quarter),
    state = case_when(
      EST_ST == "01" ~ "Alabama",
      EST_ST == "02" ~ "Alaska",
      EST_ST == "04" ~ "Arizona",
      EST_ST == "05" ~ "Arkansas",
      EST_ST == "06" ~ "California",
      EST_ST == "08" ~ "Colorado",
      EST_ST == "09" ~ "Connecticut",
      EST_ST == "10" ~ "Delaware",
      EST_ST == "11" ~ "District of Columbia",
      EST_ST == "12" ~ "Florida",
      EST_ST == "13" ~ "Georgia",
      EST_ST == "15" ~ "Hawaii",
      EST_ST == "16" ~ "Idaho",
      EST_ST == "17" ~ "Illinois",
      EST_ST == "18" ~ "Indiana",
      EST_ST == "19" ~ "Iowa",
      EST_ST == "20" ~ "Kansas",
      EST_ST == "21" ~ "Kentucky",
      EST_ST == "22" ~ "Louisiana",
      EST_ST == "23" ~ "Maine",
      EST_ST == "24" ~ "Maryland",
      EST_ST == "25" ~ "Massachusetts",
      EST_ST == "26" ~ "Michigan",
      EST_ST == "27" ~ "Minnesota",
      EST_ST == "28" ~ "Mississippi",
      EST_ST == "29" ~ "Missouri",
      EST_ST == "30" ~ "Montana",
      EST_ST == "31" ~ "Nebraska",
      EST_ST == "32" ~ "Nevada",
      EST_ST == "33" ~ "New Hampshire",
      EST_ST == "34" ~ "New Jersey",
      EST_ST == "35" ~ "New Mexico",
      EST_ST == "36" ~ "New York",
      EST_ST == "37" ~ "North Carolina",
      EST_ST == "38" ~ "North Dakota",
      EST_ST == "39" ~ "Ohio",
      EST_ST == "40" ~ "Oklahoma",
      EST_ST == "41" ~ "Oregon",
      EST_ST == "42" ~ "Pennsylvania",
      EST_ST == "44" ~ "Rhode Island",
      EST_ST == "45" ~ "South Carolina",
      EST_ST == "46" ~ "South Dakota",
      EST_ST == "47" ~ "Tennessee",
      EST_ST == "48" ~ "Texas",
      EST_ST == "49" ~ "Utah",
      EST_ST == "50" ~ "Vermont",
      EST_ST == "51" ~ "Virginia",
      EST_ST == "53" ~ "Washington",
      EST_ST == "54" ~ "West Virginia",
      EST_ST == "55" ~ "Wisconsin",
      EST_ST == "56" ~ "Wyoming"
    )
  )

# Sociodemographic characteristics
data <- data %>% 
  mutate(
    income_num = case_when(
      INCOME == 1 ~ 12500,
      INCOME == 2 ~ 30000,
      INCOME == 3 ~ 42500,
      INCOME == 4 ~ 62500,
      INCOME == 5 ~ 87500,
      INCOME == 6 ~ 125000,
      INCOME == 7 ~ 175000,
      INCOME == 8 ~ 250000,
      TRUE ~ NA_real_
    ),
    fpg = case_when( # Federal poverty guidelines
      year == 2022 & state != "Alaska" & state != "Hawaii" ~ 100 * (income_num / (8870 + 4720 * THHLD_NUMPER)),
      year == 2022 & state == "Alaska" ~ 100 * (income_num / (11090 + 5900 * THHLD_NUMPER)),
      year == 2022 & state == "Hawaii" ~ 100 * (income_num / (10200 + 5430 * THHLD_NUMPER)),
      year == 2023 & state != "Alaska" & state != "Hawaii" ~ 100 * (income_num / (9440 + 5140 * THHLD_NUMPER)),
      year == 2023 & state == "Alaska" ~ 100 * (income_num / (11780 + 6430 * THHLD_NUMPER)),
      year == 2023 & state == "Hawaii" ~ 100 * (income_num / (10860 + 5910 * THHLD_NUMPER)),
      year == 2024 & state != "Alaska" & state != "Hawaii" ~ 100 * (income_num / (9680 + 5380 * THHLD_NUMPER)),
      year == 2024 & state == "Alaska" ~ 100 * (income_num / (12080 + 6730 * THHLD_NUMPER)),
      year == 2024 & state == "Hawaii" ~ 100 * (income_num / (11120 + 6190 * THHLD_NUMPER)),
      TRUE ~ NA_real_
    ),
    age = year - TBIRTH_YEAR,
    age_cat = case_when(
      age >= 18 & age <= 24 ~ "18-24",
      age >= 25 & age <= 34 ~ "25-34",
      age >= 35 & age <= 44 ~ "35-44",
      age >= 45 & age <= 54 ~ "45-54",
      age >= 55 & age <= 64 ~ "55-64",
      age >= 65 & age <= 74 ~ "65-74",
      age >= 75 ~ ">75",
      TRUE ~ NA_character_
    ),
    sex_cat = case_when(
      EGENID_BIRTH == 1 ~ "1.Male",
      EGENID_BIRTH == 2 ~ "2.Female",
      TRUE ~ NA_character_
    ),
    race_cat = case_when(
      RRACE == 1 ~ "White",
      RRACE == 2 ~ "Black",
      RRACE == 3 ~ "Asian",
      RRACE == 4 ~ "Other",
      TRUE ~ NA_character_
    ),
    race_cat = case_when( # Note: Hispanic ethnicity overrides all other race variables
      RHISPANIC == 1 ~ race_cat,
      RHISPANIC == 2 ~ "Hispanic",
      TRUE ~ race_cat
    ),
    edu_cat = case_when(
      EEDUC == 1 ~ "Less than high school",
      EEDUC == 2 ~ "Some high school",
      EEDUC == 3 ~ "High school graduate",
      EEDUC == 4 ~ "Some college",
      EEDUC == 5 ~ "Associates degree",
      EEDUC == 6 ~ "Bachelors degree",
      EEDUC == 7 ~ "Graduate degree",
      TRUE ~ NA_character_
    ),
    bachelor_cat = case_when(
      EEDUC %in% c(6, 7) ~ 1,
      EEDUC %in% c(1, 2, 3, 4, 5) ~ 0,
      TRUE ~ NA
    )
  )

# Outcomes
## Defined insurance groups like the Urban Institute: https://github.com/UrbanInstitute/pulse_covid_feature_phase2/blob/master/scripts/01_generate_weekly_puf_data.R
## Based off of NCHS insurance groups: https://www.cdc.gov/nchs/covid19/pulse/health-insurance-coverage.htm 
data <- data %>%
  mutate(
    esi = case_when(
      HLTHINS1 == 1 ~ 1,
      HLTHINS1 == -99 & HLTHINS2 == -99 & HLTHINS3 == -99 &
          HLTHINS4 == -99 & HLTHINS5 == -99 & HLTHINS6 == -99 &
          HLTHINS7 == -99 & HLTHINS8 == -99 ~ NA, # If they didn't answer any of the health insurance questions, assign them NA
      HLTHINS1 == -88 & HLTHINS2 == -88 & HLTHINS3 == -88 &
        HLTHINS4 == -88 & HLTHINS5 == -88 & HLTHINS6 == -88 &
        HLTHINS7 == -88 & HLTHINS8 == -88 ~ NA, # If they didn't answer any of the health insurance questions, assign them NA
      TRUE ~ 0
    ),
    marketplace = case_when(
      HLTHINS2 == 1 ~ 1,
      HLTHINS1 == -99 & HLTHINS2 == -99 & HLTHINS3 == -99 &
          HLTHINS4 == -99 & HLTHINS5 == -99 & HLTHINS6 == -99 &
          HLTHINS7 == -99 & HLTHINS8 == -99 ~ NA, # If they didn't answer any of the health insurance questions, assign them NA
      HLTHINS1 == -88 & HLTHINS2 == -88 & HLTHINS3 == -88 &
        HLTHINS4 == -88 & HLTHINS5 == -88 & HLTHINS6 == -88 &
        HLTHINS7 == -88 & HLTHINS8 == -88 ~ NA, # If they didn't answer any of the health insurance questions, assign them NA
      TRUE ~ 0
    ),
    medicare = case_when(
      HLTHINS3 == 1 ~ 1,
      HLTHINS1 == -99 & HLTHINS2 == -99 & HLTHINS3 == -99 &
          HLTHINS4 == -99 & HLTHINS5 == -99 & HLTHINS6 == -99 &
          HLTHINS7 == -99 & HLTHINS8 == -99 ~ NA, # If they didn't answer any of the health insurance questions, assign them NA
      HLTHINS1 == -88 & HLTHINS2 == -88 & HLTHINS3 == -88 &
        HLTHINS4 == -88 & HLTHINS5 == -88 & HLTHINS6 == -88 &
        HLTHINS7 == -88 & HLTHINS8 == -88 ~ NA, # If they didn't answer any of the health insurance questions, assign them NA
      TRUE ~ 0
    ),
    medicaid = case_when(
      HLTHINS4 == 1 ~ 1,
      HLTHINS1 == -99 & HLTHINS2 == -99 & HLTHINS3 == -99 &
          HLTHINS4 == -99 & HLTHINS5 == -99 & HLTHINS6 == -99 &
          HLTHINS7 == -99 & HLTHINS8 == -99 ~ NA, # If they didn't answer any of the health insurance questions, assign them NA
      HLTHINS1 == -88 & HLTHINS2 == -88 & HLTHINS3 == -88 &
        HLTHINS4 == -88 & HLTHINS5 == -88 & HLTHINS6 == -88 &
        HLTHINS7 == -88 & HLTHINS8 == -88 ~ NA, # If they didn't answer any of the health insurance questions, assign them NA
      TRUE ~ 0
    ),
    tricare = case_when(
      HLTHINS5 == 1 ~ 1,
      HLTHINS1 == -99 & HLTHINS2 == -99 & HLTHINS3 == -99 &
          HLTHINS4 == -99 & HLTHINS5 == -99 & HLTHINS6 == -99 &
          HLTHINS7 == -99 & HLTHINS8 == -99 ~ NA, # If they didn't answer any of the health insurance questions, assign them NA
      HLTHINS1 == -88 & HLTHINS2 == -88 & HLTHINS3 == -88 &
        HLTHINS4 == -88 & HLTHINS5 == -88 & HLTHINS6 == -88 &
        HLTHINS7 == -88 & HLTHINS8 == -88 ~ NA, # If they didn't answer any of the health insurance questions, assign them NA
      TRUE ~ 0
    ),
    va = case_when(
      HLTHINS6 == 1 ~ 1,
      HLTHINS1 == -99 & HLTHINS2 == -99 & HLTHINS3 == -99 &
          HLTHINS4 == -99 & HLTHINS5 == -99 & HLTHINS6 == -99 &
          HLTHINS7 == -99 & HLTHINS8 == -99 ~ NA, # If they didn't answer any of the health insurance questions, assign them NA
      HLTHINS1 == -88 & HLTHINS2 == -88 & HLTHINS3 == -88 &
        HLTHINS4 == -88 & HLTHINS5 == -88 & HLTHINS6 == -88 &
        HLTHINS7 == -88 & HLTHINS8 == -88 ~ NA, # If they didn't answer any of the health insurance questions, assign them NA
      TRUE ~ 0
    ),
    ihs = case_when(
      HLTHINS7 == 1 ~ 1,
      HLTHINS1 == -99 & HLTHINS2 == -99 & HLTHINS3 == -99 &
          HLTHINS4 == -99 & HLTHINS5 == -99 & HLTHINS6 == -99 &
          HLTHINS7 == -99 & HLTHINS8 == -99 ~ NA, # If they didn't answer any of the health insurance questions, assign them NA
      HLTHINS1 == -88 & HLTHINS2 == -88 & HLTHINS3 == -88 &
        HLTHINS4 == -88 & HLTHINS5 == -88 & HLTHINS6 == -88 &
        HLTHINS7 == -88 & HLTHINS8 == -88 ~ NA, # If they didn't answer any of the health insurance questions, assign them NA
      TRUE ~ 0
    ),
    other_hi = case_when(
      HLTHINS8 == 1 ~ 1,
      HLTHINS1 == -99 & HLTHINS2 == -99 & HLTHINS3 == -99 &
          HLTHINS4 == -99 & HLTHINS5 == -99 & HLTHINS6 == -99 &
          HLTHINS7 == -99 & HLTHINS8 == -99 ~ NA, # If they didn't answer any of the health insurance questions, assign them NA
      HLTHINS1 == -88 & HLTHINS2 == -88 & HLTHINS3 == -88 &
        HLTHINS4 == -88 & HLTHINS5 == -88 & HLTHINS6 == -88 &
        HLTHINS7 == -88 & HLTHINS8 == -88 ~ NA, # If they didn't answer any of the health insurance questions, assign them NA
      TRUE ~ 0
    ),
    uninsured = case_when(
      HLTHINS1 == 1 |
        HLTHINS2 == 1 |
        HLTHINS3 == 1 |
        HLTHINS4 == 1 |
        HLTHINS5 == 1 |
        HLTHINS6 == 1 ~ 0,
      HLTHINS1 == 2 &
        HLTHINS2 == 2 &
        HLTHINS3 == 2 &
        HLTHINS4 == 2 &
        HLTHINS5 == 2 &
        HLTHINS6 == 2 ~ 1,
      HLTHINS7 == 1 ~ 1, # Census includes those who have Indian Health Service coverage as uninsured
      TRUE ~ NA
    ),
    employed = case_when(
      ANYWORK == 1 ~ 1, 
      ANYWORK == 2 ~ 0, 
      TRUE ~ NA
      ),
    not_missing_hi = case_when(
      HLTHINS1 %in% c(1, 2) | 
        HLTHINS2 %in% c(1, 2) | 
        HLTHINS3 %in% c(1, 2) | 
        HLTHINS4 %in% c(1, 2) | 
        HLTHINS5 %in% c(1, 2) | 
        HLTHINS6 %in% c(1, 2) ~ 1,
      TRUE ~ NA
    ),
    not_missing_employment = case_when(
      ANYWORK %in% c(1, 2) ~ 1,
      TRUE ~ NA
    )
  )

# DID setup
data <- data %>% 
  mutate(
    post = case_when( 
      # Blank out March 29, 2023 to July 10, 2023
      date < ymd("2023-03-29") ~ FALSE,
      date > ymd("2023-07-10") ~ TRUE,
      TRUE ~ NA
    ),
    intervention1 = case_when(
      state == "Georgia" ~ TRUE,
      state == "South Dakota" ~ FALSE,
      TRUE ~ NA
    ),
    intervention2 = case_when( # We tested this group but excluded it from the final analysis
      state == "Georgia" ~ TRUE,
      state %in% c("Alabama", "Florida", "Texas", "Mississippi") ~ FALSE,
      TRUE ~ NA
    ),
    intervention3 = case_when(
      state == "Georgia" ~ TRUE,
      state %in% c("Alabama", "Florida", "Texas", "Mississippi", "South Carolina") ~ FALSE,
      TRUE ~ NA
    )
  )
```

# Create survey object
```{r}
survey <- data %>%
  as_survey_rep(
    repweights = dplyr::matches("PWEIGHT[0-9]+"),
    weights = PWEIGHT_divided,
    type = "successive-difference",
    mse = TRUE
  )
```

# Select samples
```{r}
# Georgia vs. South Dakota
sample1 <- survey %>%
  subset(
    intervention1 %in% c(FALSE, TRUE) & # Intervention or control group
      age >= 19 & age <= 64 & # 19-64 years old
      fpg <= 100 & # Income up to 100% FPL
      not_missing_hi == 1 & # Health insurance not missing
      not_missing_employment == 1 # Employment not missing
  )

# Georgia vs. South Dakota - 65+
sample1_65 <- survey %>%
  subset(
    intervention1 %in% c(FALSE, TRUE) & # Intervention or control group
      age >= 65 & # 65+ years old
      fpg <= 100 & # Income up to 100% FPL
      not_missing_hi == 1 & # Health insurance not missing
      not_missing_employment == 1 # Employment not missing
  )

# Georgia vs. South Dakota - 65+ Medicare
sample1_65_medicare <- survey %>%
  subset(
    intervention1 %in% c(FALSE, TRUE) & # Intervention or control group
      age >= 65 & # 65+ years old
      medicare == TRUE & # Medicare beneficiaries
      not_missing_hi == 1 & # Health insurance not missing
      not_missing_employment == 1 # Employment not missing
  )

# Georgia vs. South Dakota - 70+
sample1_70 <- survey %>%
  subset(
    intervention1 %in% c(FALSE, TRUE) & # Intervention or control group
      age >= 70 & # 70+ years old
      fpg <= 100 & # Income up to 100% FPL
      not_missing_hi == 1 & # Health insurance not missing
      not_missing_employment == 1 # Employment not missing
  )

# Georgia vs. South Dakota - 70+ Medicare
sample1_70_medicare <- survey %>%
  subset(
    intervention1 %in% c(FALSE, TRUE) & # Intervention or control group
      age >= 70 & # 70+ years old
      medicare == TRUE &
      not_missing_hi == 1 & # Health insurance not missing
      not_missing_employment == 1 # Employment not missing
  )

# Georgia vs. South Dakota - >200% FPL
sample1_200 <- survey %>%
  subset(
    intervention1 %in% c(FALSE, TRUE) & # Intervention or control group
      age >= 19 & age <= 64 & # 19-64 years old
      fpg >= 200 & # Income over 200% FPL
      not_missing_hi == 1 & # Health insurance not missing
      not_missing_employment == 1 # Employment not missing
  )

# Subset to pre-period
sample1_pre <- sample1 %>% subset(post == FALSE)
sample1_65_pre <- sample1_65 %>% subset(post == FALSE)

# Subset to post-period
sample1_post <- sample1 %>% subset(post == TRUE)
sample1_65_post <- sample1_65 %>% subset(post == TRUE)

# Georgia vs. Alabama, Florida, Texas, Mississippi, South Carolina
sample3 <- survey %>%
  subset(
    intervention3 %in% c(FALSE, TRUE) & # Intervention or control group
      age >= 19 & age <= 64 & # 19-64 years old
      fpg <= 100 & # Income up to 100% FPL
      not_missing_hi == 1 & # Health insurance not missing
      not_missing_employment == 1 # Employment not missing
  )

# Georgia vs. Alabama, Florida, Texas, Mississippi, South Carolina - 65+
sample3_65 <- survey %>%
  subset(
    intervention3 %in% c(FALSE, TRUE) & # Intervention or control group
      age >= 65 & # 65+ years old
      fpg <= 100 & # Income up to 100% FPL
      not_missing_hi == 1 & # Health insurance not missing
      not_missing_employment == 1 # Employment not missing
  )

# Subset to pre-period
sample3_pre <- sample3 %>% subset(post == FALSE)
sample3_65_pre <- sample3_65 %>% subset(post == FALSE)

# Subset to post-period
sample3_post <- sample3 %>% subset(post == TRUE)
sample3_65_post <- sample3_65 %>% subset(post == TRUE)
```

# Plot data
### GA v SD 19-64
```{r}
# Medicaid
medicaid_quarter <- svyby(~medicaid, ~quarter_factor + intervention1, sample1,
                       svymean, vartype = "se", na.rm = TRUE) %>%
  as.data.frame() %>%
  rename(
    percentage = medicaid,
    se = se
  ) %>%
  mutate(
    percentage = percentage * 100,
    se = se * 100,
    lower = pmax(percentage - 1.96 * se, 0),
    upper = pmin(percentage + 1.96 * se, 100)
  ) %>%
  filter(quarter_factor != "2023 Q2")

policy_change_x <- which(levels(medicaid_quarter$quarter_factor) == "2023 Q2") + (1/3)

medicaid_quarter_plot <- ggplot(medicaid_quarter, aes(x = quarter_factor, y = percentage, color = intervention1, group = intervention1)) +
  geom_line() +
  geom_point() +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2) +
  geom_vline(xintercept = policy_change_x, linetype = "dashed", color = "black") +  # Policy change in July 2023
  labs(
    x = "Date",
    y = "Medicaid coverage, %"
  ) +
  scale_x_discrete(labels = c("Mar 2022", "Jun 2022", "Sep 2022", "Dec 2022", 
                              "Mar 2023", "Jun 2023", "Sep 2023", "Dec 2023",
                              "Mar 2024", "Jun 2024", "Sep 2024"),
                   drop = FALSE) +
  scale_color_brewer(palette = "Set1", labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    legend.title = element_blank()
  ) +
  ylim(0, 100)

medicaid_quarter_plot
ggsave("medicaid_quarter_plot.jpg")

# Uninsured
uninsured_quarter <- svyby(~uninsured, ~quarter_factor + intervention1, sample1,
                       svymean, vartype = "se", na.rm = TRUE) %>%
  as.data.frame() %>%
  rename(
    percentage = uninsured,
    se = se
  ) %>%
  mutate(
    percentage = percentage * 100,
    se = se * 100,
    lower = pmax(percentage - 1.96 * se, 0),
    upper = pmin(percentage + 1.96 * se, 100)
  ) %>%
  filter(quarter_factor != "2023 Q2")

policy_change_x <- which(levels(uninsured_quarter$quarter_factor) == "2023 Q2") + (1/3)

uninsured_quarter_plot <- ggplot(uninsured_quarter, aes(x = quarter_factor, y = percentage, color = intervention1, group = intervention1)) +
  geom_line() +
  geom_point() +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2) +
  geom_vline(xintercept = policy_change_x, linetype = "dashed", color = "black") +  # Policy change in July 2023
  labs(
    x = "Date",
    y = "Uninsured rate, %"
  ) +
  scale_x_discrete(labels = c("Mar 2022", "Jun 2022", "Sep 2022", "Dec 2022", 
                              "Mar 2023", "Jun 2023", "Sep 2023", "Dec 2023",
                              "Mar 2024", "Jun 2024", "Sep 2024"),
                   drop = FALSE) +
  scale_color_brewer(palette = "Set1", labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    legend.title = element_blank()
  ) +
  ylim(0, 100)

uninsured_quarter_plot
ggsave("uninsured_quarter_plot.jpg")

# Employed
employed_quarter <- svyby(~employed, ~quarter_factor + intervention1, sample1,
                       svymean, vartype = "se", na.rm = TRUE) %>%
  as.data.frame() %>%
  rename(
    percentage = employed,
    se = se
  ) %>%
  mutate(
    percentage = percentage * 100,
    se = se * 100,
    lower = pmax(percentage - 1.96 * se, 0),
    upper = pmin(percentage + 1.96 * se, 100)
  ) %>%
  filter(quarter_factor != "2023 Q2")

policy_change_x <- which(levels(employed_quarter$quarter_factor) == "2023 Q2") + (1/3)

employed_quarter_plot <- ggplot(employed_quarter, aes(x = quarter_factor, y = percentage, color = intervention1, group = intervention1)) +
  geom_line() +
  geom_point() +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2) +
  geom_vline(xintercept = policy_change_x, linetype = "dashed", color = "black") +  # Policy change in July 2023
  labs(
    x = "Date",
    y = "Employment, %"
  ) +
  scale_x_discrete(labels = c("Mar 2022", "Jun 2022", "Sep 2022", "Dec 2022", 
                              "Mar 2023", "Jun 2023", "Sep 2023", "Dec 2023",
                              "Mar 2024", "Jun 2024", "Sep 2024"),
                   drop = FALSE) +
  scale_color_brewer(palette = "Set1", labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    legend.title = element_blank()
  ) +
  ylim(0, 100)

employed_quarter_plot
ggsave("employed_quarter_plot.jpg")
```

### GA v non-expansion 19-64
```{r}
# Medicaid
medicaid_quarter <- svyby(~medicaid, ~quarter_factor + intervention3, sample3,
                       svymean, vartype = "se", na.rm = TRUE) %>%
  as.data.frame() %>%
  rename(
    percentage = medicaid,
    se = se
  ) %>%
  mutate(
    percentage = percentage * 100,
    se = se * 100,
    lower = pmax(percentage - 1.96 * se, 0),
    upper = pmin(percentage + 1.96 * se, 100)
  ) %>%
  filter(quarter_factor != "2023 Q2")

policy_change_x <- which(levels(medicaid_quarter$quarter_factor) == "2023 Q2") + (1/3)

medicaid_quarter_plot <- ggplot(medicaid_quarter, aes(x = quarter_factor, y = percentage, color = intervention3, group = intervention3)) +
  geom_line() +
  geom_point() +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2) +
  geom_vline(xintercept = policy_change_x, linetype = "dashed", color = "black") +  # Policy change in July 2023
  labs(
    x = "Date",
    y = "Medicaid coverage, %"
  ) +
  scale_x_discrete(labels = c("Mar 2022", "Jun 2022", "Sep 2022", "Dec 2022", 
                              "Mar 2023", "Jun 2023", "Sep 2023", "Dec 2023",
                              "Mar 2024", "Jun 2024", "Sep 2024"),
                   drop = FALSE) +
  scale_color_brewer(palette = "Set1", labels = c("Non-expansion states", "Georgia")) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    legend.title = element_blank()
  ) +
  ylim(0, 100)

medicaid_quarter_plot
ggsave("medicaid_quarter_plot_south.jpg")

# Uninsured
uninsured_quarter <- svyby(~uninsured, ~quarter_factor + intervention3, sample3,
                       svymean, vartype = "se", na.rm = TRUE) %>%
  as.data.frame() %>%
  rename(
    percentage = uninsured,
    se = se
  ) %>%
  mutate(
    percentage = percentage * 100,
    se = se * 100,
    lower = pmax(percentage - 1.96 * se, 0),
    upper = pmin(percentage + 1.96 * se, 100)
  ) %>%
  filter(quarter_factor != "2023 Q2")

policy_change_x <- which(levels(uninsured_quarter$quarter_factor) == "2023 Q2") + (1/3)

uninsured_quarter_plot <- ggplot(uninsured_quarter, aes(x = quarter_factor, y = percentage, color = intervention3, group = intervention3)) +
  geom_line() +
  geom_point() +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2) +
  geom_vline(xintercept = policy_change_x, linetype = "dashed", color = "black") +  # Policy change in July 2023
  labs(
    x = "Date",
    y = "Uninsured, %"
  ) +
  scale_x_discrete(labels = c("Mar 2022", "Jun 2022", "Sep 2022", "Dec 2022", 
                              "Mar 2023", "Jun 2023", "Sep 2023", "Dec 2023",
                              "Mar 2024", "Jun 2024", "Sep 2024"),
                   drop = FALSE) +
  scale_color_brewer(palette = "Set1", labels = c("Non-expansion states", "Georgia")) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    legend.title = element_blank()
  ) +
  ylim(0, 100)

uninsured_quarter_plot
ggsave("uninsured_quarter_plot_south.jpg")

# Employed
employed_quarter <- svyby(~employed, ~quarter_factor + intervention3, sample3,
                       svymean, vartype = "se", na.rm = TRUE) %>%
  as.data.frame() %>%
  rename(
    percentage = employed,
    se = se
  ) %>%
  mutate(
    percentage = percentage * 100,
    se = se * 100,
    lower = pmax(percentage - 1.96 * se, 0),
    upper = pmin(percentage + 1.96 * se, 100)
  ) %>%
  filter(quarter_factor != "2023 Q2")

policy_change_x <- which(levels(employed_quarter$quarter_factor) == "2023 Q2") + (1/3)

employed_quarter_plot <- ggplot(employed_quarter, aes(x = quarter_factor, y = percentage, color = intervention3, group = intervention3)) +
  geom_line() +
  geom_point() +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2) +
  geom_vline(xintercept = policy_change_x, linetype = "dashed", color = "black") +  # Policy change in July 2023
  labs(
    x = "Date",
    y = "Employment, %"
  ) +
  scale_x_discrete(labels = c("Mar 2022", "Jun 2022", "Sep 2022", "Dec 2022", 
                              "Mar 2023", "Jun 2023", "Sep 2023", "Dec 2023",
                              "Mar 2024", "Jun 2024", "Sep 2024"),
                   drop = FALSE) +
  scale_color_brewer(palette = "Set1", labels = c("Non-expansion states", "Georgia")) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    legend.title = element_blank()
  ) +
  ylim(0, 100)

employed_quarter_plot
ggsave("employed_quarter_plot_south.jpg")
```

### GA v SD >65
```{r}
# Medicaid
medicaid_quarter <- svyby(~medicaid, ~quarter_factor + intervention1, sample1_65,
                       svymean, vartype = "se", na.rm = TRUE) %>%
  as.data.frame() %>%
  rename(
    percentage = medicaid,
    se = se
  ) %>%
  mutate(
    percentage = percentage * 100,
    se = se * 100,
    lower = pmax(percentage - 1.96 * se, 0),
    upper = pmin(percentage + 1.96 * se, 100)
  ) %>%
  filter(quarter_factor != "2023 Q2")

policy_change_x <- which(levels(medicaid_quarter$quarter_factor) == "2023 Q2") + (1/3)

medicaid_quarter_plot <- ggplot(medicaid_quarter, aes(x = quarter_factor, y = percentage, color = intervention1, group = intervention1)) +
  geom_line() +
  geom_point() +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2) +
  geom_vline(xintercept = policy_change_x, linetype = "dashed", color = "black") +  # Policy change in July 2023
  labs(
    x = "Date",
    y = "Medicaid coverage, %"
  ) +
  scale_x_discrete(labels = c("Mar 2022", "Jun 2022", "Sep 2022", "Dec 2022", 
                              "Mar 2023", "Jun 2023", "Sep 2023", "Dec 2023",
                              "Mar 2024", "Jun 2024", "Sep 2024"),
                   drop = FALSE) +
  scale_color_brewer(palette = "Set1", labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    legend.title = element_blank()
  ) +
  ylim(0, 100)

medicaid_quarter_plot
ggsave("medicaid_quarter_plot_65.jpg")

# Uninsured
uninsured_quarter <- svyby(~uninsured, ~quarter_factor + intervention1, sample1_65,
                       svymean, vartype = "se", na.rm = TRUE) %>%
  as.data.frame() %>%
  rename(
    percentage = uninsured,
    se = se
  ) %>%
  mutate(
    percentage = percentage * 100,
    se = se * 100,
    lower = pmax(percentage - 1.96 * se, 0),
    upper = pmin(percentage + 1.96 * se, 100)
  ) %>%
  filter(quarter_factor != "2023 Q2")

policy_change_x <- which(levels(uninsured_quarter$quarter_factor) == "2023 Q2") + (1/3)

uninsured_quarter_plot <- ggplot(uninsured_quarter, aes(x = quarter_factor, y = percentage, color = intervention1, group = intervention1)) +
  geom_line() +
  geom_point() +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2) +
  geom_vline(xintercept = policy_change_x, linetype = "dashed", color = "black") +  # Policy change in July 2023
  labs(
    x = "Date",
    y = "Uninsured rate, %"
  ) +
  scale_x_discrete(labels = c("Mar 2022", "Jun 2022", "Sep 2022", "Dec 2022", 
                              "Mar 2023", "Jun 2023", "Sep 2023", "Dec 2023",
                              "Mar 2024", "Jun 2024", "Sep 2024"),
                   drop = FALSE) +
  scale_color_brewer(palette = "Set1", labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    legend.title = element_blank()
  ) +
  ylim(0, 100)

uninsured_quarter_plot
ggsave("uninsured_quarter_plot_65.jpg")

# Employed
employed_quarter <- svyby(~employed, ~quarter_factor + intervention1, sample1_65,
                       svymean, vartype = "se", na.rm = TRUE) %>%
  as.data.frame() %>%
  rename(
    percentage = employed,
    se = se
  ) %>%
  mutate(
    percentage = percentage * 100,
    se = se * 100,
    lower = pmax(percentage - 1.96 * se, 0),
    upper = pmin(percentage + 1.96 * se, 100)
  ) %>%
  filter(quarter_factor != "2023 Q2")

policy_change_x <- which(levels(employed_quarter$quarter_factor) == "2023 Q2") + (1/3)

employed_quarter_plot <- ggplot(employed_quarter, aes(x = quarter_factor, y = percentage, color = intervention1, group = intervention1)) +
  geom_line() +
  geom_point() +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2) +
  geom_vline(xintercept = policy_change_x, linetype = "dashed", color = "black") +  # Policy change in July 2023
  labs(
    x = "Date",
    y = "Employment, %"
  ) +
  scale_x_discrete(labels = c("Mar 2022", "Jun 2022", "Sep 2022", "Dec 2022", 
                              "Mar 2023", "Jun 2023", "Sep 2023", "Dec 2023",
                              "Mar 2024", "Jun 2024", "Sep 2024"),
                   drop = FALSE) +
  scale_color_brewer(palette = "Set1", labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    legend.title = element_blank()
  ) +
  ylim(0, 100)

employed_quarter_plot
ggsave("employed_quarter_plot_65.jpg")
```


### GA v SD >65 Medicare
```{r}
# Medicaid
medicaid_quarter <- svyby(~medicaid, ~quarter_factor + intervention1, sample1_65_medicare,
                       svymean, vartype = "se", na.rm = TRUE) %>%
  as.data.frame() %>%
  rename(
    percentage = medicaid,
    se = se
  ) %>%
  mutate(
    percentage = percentage * 100,
    se = se * 100,
    lower = pmax(percentage - 1.96 * se, 0),
    upper = pmin(percentage + 1.96 * se, 100)
  ) %>%
  filter(quarter_factor != "2023 Q2")

policy_change_x <- which(levels(medicaid_quarter$quarter_factor) == "2023 Q2") + (1/3)

medicaid_quarter_plot <- ggplot(medicaid_quarter, aes(x = quarter_factor, y = percentage, color = intervention1, group = intervention1)) +
  geom_line() +
  geom_point() +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2) +
  geom_vline(xintercept = policy_change_x, linetype = "dashed", color = "black") +  # Policy change in July 2023
  labs(
    x = "Date",
    y = "Medicaid coverage, %"
  ) +
  scale_x_discrete(labels = c("Mar 2022", "Jun 2022", "Sep 2022", "Dec 2022", 
                              "Mar 2023", "Jun 2023", "Sep 2023", "Dec 2023",
                              "Mar 2024", "Jun 2024", "Sep 2024"),
                   drop = FALSE) +
  scale_color_brewer(palette = "Set1", labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    legend.title = element_blank()
  ) +
  ylim(0, 100)

medicaid_quarter_plot
ggsave("medicaid_quarter_plot_65_medicare.jpg")

# Uninsured
uninsured_quarter <- svyby(~uninsured, ~quarter_factor + intervention1, sample1_65_medicare,
                       svymean, vartype = "se", na.rm = TRUE) %>%
  as.data.frame() %>%
  rename(
    percentage = uninsured,
    se = se
  ) %>%
  mutate(
    percentage = percentage * 100,
    se = se * 100,
    lower = pmax(percentage - 1.96 * se, 0),
    upper = pmin(percentage + 1.96 * se, 100)
  ) %>%
  filter(quarter_factor != "2023 Q2")

policy_change_x <- which(levels(uninsured_quarter$quarter_factor) == "2023 Q2") + (1/3)

uninsured_quarter_plot <- ggplot(uninsured_quarter, aes(x = quarter_factor, y = percentage, color = intervention1, group = intervention1)) +
  geom_line() +
  geom_point() +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2) +
  geom_vline(xintercept = policy_change_x, linetype = "dashed", color = "black") +  # Policy change in July 2023
  labs(
    x = "Date",
    y = "Uninsured rate, %"
  ) +
  scale_x_discrete(labels = c("Mar 2022", "Jun 2022", "Sep 2022", "Dec 2022", 
                              "Mar 2023", "Jun 2023", "Sep 2023", "Dec 2023",
                              "Mar 2024", "Jun 2024", "Sep 2024"),
                   drop = FALSE) +
  scale_color_brewer(palette = "Set1", labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    legend.title = element_blank()
  ) +
  ylim(0, 100)

uninsured_quarter_plot
ggsave("uninsured_quarter_plot_65_medicare.jpg")

# Employed
employed_quarter <- svyby(~employed, ~quarter_factor + intervention1, sample1_65_medicare,
                       svymean, vartype = "se", na.rm = TRUE) %>%
  as.data.frame() %>%
  rename(
    percentage = employed,
    se = se
  ) %>%
  mutate(
    percentage = percentage * 100,
    se = se * 100,
    lower = pmax(percentage - 1.96 * se, 0),
    upper = pmin(percentage + 1.96 * se, 100)
  ) %>%
  filter(quarter_factor != "2023 Q2")

policy_change_x <- which(levels(employed_quarter$quarter_factor) == "2023 Q2") + (1/3)

employed_quarter_plot <- ggplot(employed_quarter, aes(x = quarter_factor, y = percentage, color = intervention1, group = intervention1)) +
  geom_line() +
  geom_point() +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2) +
  geom_vline(xintercept = policy_change_x, linetype = "dashed", color = "black") +  # Policy change in July 2023
  labs(
    x = "Date",
    y = "Employment, %"
  ) +
  scale_x_discrete(labels = c("Mar 2022", "Jun 2022", "Sep 2022", "Dec 2022", 
                              "Mar 2023", "Jun 2023", "Sep 2023", "Dec 2023",
                              "Mar 2024", "Jun 2024", "Sep 2024"),
                   drop = FALSE) +
  scale_color_brewer(palette = "Set1", labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    legend.title = element_blank()
  ) +
  ylim(0, 100)

employed_quarter_plot
ggsave("employed_quarter_plot_65_medicare.jpg")
```

### GA v SD >70
```{r}
# Medicaid
medicaid_quarter <- svyby(~medicaid, ~quarter_factor + intervention1, sample1_70,
                       svymean, vartype = "se", na.rm = TRUE) %>%
  as.data.frame() %>%
  rename(
    percentage = medicaid,
    se = se
  ) %>%
  mutate(
    percentage = percentage * 100,
    se = se * 100,
    lower = pmax(percentage - 1.96 * se, 0),
    upper = pmin(percentage + 1.96 * se, 100)
  ) %>%
  filter(quarter_factor != "2023 Q2")

policy_change_x <- which(levels(medicaid_quarter$quarter_factor) == "2023 Q2") + (1/3)

medicaid_quarter_plot <- ggplot(medicaid_quarter, aes(x = quarter_factor, y = percentage, color = intervention1, group = intervention1)) +
  geom_line() +
  geom_point() +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2) +
  geom_vline(xintercept = policy_change_x, linetype = "dashed", color = "black") +  # Policy change in July 2023
  labs(
    x = "Date",
    y = "Medicaid coverage, %"
  ) +
  scale_x_discrete(labels = c("Mar 2022", "Jun 2022", "Sep 2022", "Dec 2022", 
                              "Mar 2023", "Jun 2023", "Sep 2023", "Dec 2023",
                              "Mar 2024", "Jun 2024", "Sep 2024"),
                   drop = FALSE) +
  scale_color_brewer(palette = "Set1", labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    legend.title = element_blank()
  ) +
  ylim(0, 100)

medicaid_quarter_plot
ggsave("medicaid_quarter_plot_70.jpg")

# Uninsured
uninsured_quarter <- svyby(~uninsured, ~quarter_factor + intervention1, sample1_70,
                       svymean, vartype = "se", na.rm = TRUE) %>%
  as.data.frame() %>%
  rename(
    percentage = uninsured,
    se = se
  ) %>%
  mutate(
    percentage = percentage * 100,
    se = se * 100,
    lower = pmax(percentage - 1.96 * se, 0),
    upper = pmin(percentage + 1.96 * se, 100)
  ) %>%
  filter(quarter_factor != "2023 Q2")

policy_change_x <- which(levels(uninsured_quarter$quarter_factor) == "2023 Q2") + (1/3)

uninsured_quarter_plot <- ggplot(uninsured_quarter, aes(x = quarter_factor, y = percentage, color = intervention1, group = intervention1)) +
  geom_line() +
  geom_point() +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2) +
  geom_vline(xintercept = policy_change_x, linetype = "dashed", color = "black") +  # Policy change in July 2023
  labs(
    x = "Date",
    y = "Uninsured rate, %"
  ) +
  scale_x_discrete(labels = c("Mar 2022", "Jun 2022", "Sep 2022", "Dec 2022", 
                              "Mar 2023", "Jun 2023", "Sep 2023", "Dec 2023",
                              "Mar 2024", "Jun 2024", "Sep 2024"),
                   drop = FALSE) +
  scale_color_brewer(palette = "Set1", labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    legend.title = element_blank()
  ) +
  ylim(0, 100)

uninsured_quarter_plot
ggsave("uninsured_quarter_plot_70.jpg")

# Employed
employed_quarter <- svyby(~employed, ~quarter_factor + intervention1, sample1_70,
                       svymean, vartype = "se", na.rm = TRUE) %>%
  as.data.frame() %>%
  rename(
    percentage = employed,
    se = se
  ) %>%
  mutate(
    percentage = percentage * 100,
    se = se * 100,
    lower = pmax(percentage - 1.96 * se, 0),
    upper = pmin(percentage + 1.96 * se, 100)
  ) %>%
  filter(quarter_factor != "2023 Q2")

policy_change_x <- which(levels(employed_quarter$quarter_factor) == "2023 Q2") + (1/3)

employed_quarter_plot <- ggplot(employed_quarter, aes(x = quarter_factor, y = percentage, color = intervention1, group = intervention1)) +
  geom_line() +
  geom_point() +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2) +
  geom_vline(xintercept = policy_change_x, linetype = "dashed", color = "black") +  # Policy change in July 2023
  labs(
    x = "Date",
    y = "Employment, %"
  ) +
  scale_x_discrete(labels = c("Mar 2022", "Jun 2022", "Sep 2022", "Dec 2022", 
                              "Mar 2023", "Jun 2023", "Sep 2023", "Dec 2023",
                              "Mar 2024", "Jun 2024", "Sep 2024"),
                   drop = FALSE) +
  scale_color_brewer(palette = "Set1", labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    legend.title = element_blank()
  ) +
  ylim(0, 100)

employed_quarter_plot
ggsave("employed_quarter_plot_70.jpg")
```



### GA v SD >70 Medicare
```{r}
# Medicaid
medicaid_quarter <- svyby(~medicaid, ~quarter_factor + intervention1, sample1_70_medicare,
                       svymean, vartype = "se", na.rm = TRUE) %>%
  as.data.frame() %>%
  rename(
    percentage = medicaid,
    se = se
  ) %>%
  mutate(
    percentage = percentage * 100,
    se = se * 100,
    lower = pmax(percentage - 1.96 * se, 0),
    upper = pmin(percentage + 1.96 * se, 100)
  ) %>%
  filter(quarter_factor != "2023 Q2")

policy_change_x <- which(levels(medicaid_quarter$quarter_factor) == "2023 Q2") + (1/3)

medicaid_quarter_plot <- ggplot(medicaid_quarter, aes(x = quarter_factor, y = percentage, color = intervention1, group = intervention1)) +
  geom_line() +
  geom_point() +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2) +
  geom_vline(xintercept = policy_change_x, linetype = "dashed", color = "black") +  # Policy change in July 2023
  labs(
    x = "Date",
    y = "Medicaid coverage, %"
  ) +
  scale_x_discrete(labels = c("Mar 2022", "Jun 2022", "Sep 2022", "Dec 2022", 
                              "Mar 2023", "Jun 2023", "Sep 2023", "Dec 2023",
                              "Mar 2024", "Jun 2024", "Sep 2024"),
                   drop = FALSE) +
  scale_color_brewer(palette = "Set1", labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    legend.title = element_blank()
  ) +
  ylim(0, 100)

medicaid_quarter_plot
ggsave("medicaid_quarter_plot_70_medicare.jpg")

# Uninsured
uninsured_quarter <- svyby(~uninsured, ~quarter_factor + intervention1, sample1_70_medicare,
                       svymean, vartype = "se", na.rm = TRUE) %>%
  as.data.frame() %>%
  rename(
    percentage = uninsured,
    se = se
  ) %>%
  mutate(
    percentage = percentage * 100,
    se = se * 100,
    lower = pmax(percentage - 1.96 * se, 0),
    upper = pmin(percentage + 1.96 * se, 100)
  ) %>%
  filter(quarter_factor != "2023 Q2")

policy_change_x <- which(levels(uninsured_quarter$quarter_factor) == "2023 Q2") + (1/3)

uninsured_quarter_plot <- ggplot(uninsured_quarter, aes(x = quarter_factor, y = percentage, color = intervention1, group = intervention1)) +
  geom_line() +
  geom_point() +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2) +
  geom_vline(xintercept = policy_change_x, linetype = "dashed", color = "black") +  # Policy change in July 2023
  labs(
    x = "Date",
    y = "Uninsured rate, %"
  ) +
  scale_x_discrete(labels = c("Mar 2022", "Jun 2022", "Sep 2022", "Dec 2022", 
                              "Mar 2023", "Jun 2023", "Sep 2023", "Dec 2023",
                              "Mar 2024", "Jun 2024", "Sep 2024"),
                   drop = FALSE) +
  scale_color_brewer(palette = "Set1", labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    legend.title = element_blank()
  ) +
  ylim(0, 100)

uninsured_quarter_plot
ggsave("uninsured_quarter_plot_70_medicare.jpg")

# Employed
employed_quarter <- svyby(~employed, ~quarter_factor + intervention1, sample1_70_medicare,
                       svymean, vartype = "se", na.rm = TRUE) %>%
  as.data.frame() %>%
  rename(
    percentage = employed,
    se = se
  ) %>%
  mutate(
    percentage = percentage * 100,
    se = se * 100,
    lower = pmax(percentage - 1.96 * se, 0),
    upper = pmin(percentage + 1.96 * se, 100)
  ) %>%
  filter(quarter_factor != "2023 Q2")

policy_change_x <- which(levels(employed_quarter$quarter_factor) == "2023 Q2") + (1/3)

employed_quarter_plot <- ggplot(employed_quarter, aes(x = quarter_factor, y = percentage, color = intervention1, group = intervention1)) +
  geom_line() +
  geom_point() +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2) +
  geom_vline(xintercept = policy_change_x, linetype = "dashed", color = "black") +  # Policy change in July 2023
  labs(
    x = "Date",
    y = "Employment, %"
  ) +
  scale_x_discrete(labels = c("Mar 2022", "Jun 2022", "Sep 2022", "Dec 2022", 
                              "Mar 2023", "Jun 2023", "Sep 2023", "Dec 2023",
                              "Mar 2024", "Jun 2024", "Sep 2024"),
                   drop = FALSE) +
  scale_color_brewer(palette = "Set1", labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    legend.title = element_blank()
  ) +
  ylim(0, 100)

employed_quarter_plot
ggsave("employed_quarter_plot_70_medicare.jpg")
```

### GA v SD >200% FPL
```{r}
# Medicaid
medicaid_quarter <- svyby(~medicaid, ~quarter_factor + intervention1, sample1_200,
                       svymean, vartype = "se", na.rm = TRUE) %>%
  as.data.frame() %>%
  rename(
    percentage = medicaid,
    se = se
  ) %>%
  mutate(
    percentage = percentage * 100,
    se = se * 100,
    lower = pmax(percentage - 1.96 * se, 0),
    upper = pmin(percentage + 1.96 * se, 100)
  ) %>%
  filter(quarter_factor != "2023 Q2")

policy_change_x <- which(levels(medicaid_quarter$quarter_factor) == "2023 Q2") + (1/3)

medicaid_quarter_plot <- ggplot(medicaid_quarter, aes(x = quarter_factor, y = percentage, color = intervention1, group = intervention1)) +
  geom_line() +
  geom_point() +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2) +
  geom_vline(xintercept = policy_change_x, linetype = "dashed", color = "black") +  # Policy change in July 2023
  labs(
    x = "Date",
    y = "Medicaid coverage, %"
  ) +
  scale_x_discrete(labels = c("Mar 2022", "Jun 2022", "Sep 2022", "Dec 2022", 
                              "Mar 2023", "Jun 2023", "Sep 2023", "Dec 2023",
                              "Mar 2024", "Jun 2024", "Sep 2024"),
                   drop = FALSE) +
  scale_color_brewer(palette = "Set1", labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    legend.title = element_blank()
  ) +
  ylim(0, 100)

medicaid_quarter_plot
ggsave("medicaid_quarter_plot_200.jpg")

# Uninsured
uninsured_quarter <- svyby(~uninsured, ~quarter_factor + intervention1, sample1_200,
                       svymean, vartype = "se", na.rm = TRUE) %>%
  as.data.frame() %>%
  rename(
    percentage = uninsured,
    se = se
  ) %>%
  mutate(
    percentage = percentage * 100,
    se = se * 100,
    lower = pmax(percentage - 1.96 * se, 0),
    upper = pmin(percentage + 1.96 * se, 100)
  ) %>%
  filter(quarter_factor != "2023 Q2")

policy_change_x <- which(levels(uninsured_quarter$quarter_factor) == "2023 Q2") + (1/3)

uninsured_quarter_plot <- ggplot(uninsured_quarter, aes(x = quarter_factor, y = percentage, color = intervention1, group = intervention1)) +
  geom_line() +
  geom_point() +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2) +
  geom_vline(xintercept = policy_change_x, linetype = "dashed", color = "black") +  # Policy change in July 2023
  labs(
    x = "Date",
    y = "Uninsured rate, %"
  ) +
  scale_x_discrete(labels = c("Mar 2022", "Jun 2022", "Sep 2022", "Dec 2022", 
                              "Mar 2023", "Jun 2023", "Sep 2023", "Dec 2023",
                              "Mar 2024", "Jun 2024", "Sep 2024"),
                   drop = FALSE) +
  scale_color_brewer(palette = "Set1", labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    legend.title = element_blank()
  ) +
  ylim(0, 100)

uninsured_quarter_plot
ggsave("uninsured_quarter_plot_200.jpg")

# Employed
employed_quarter <- svyby(~employed, ~quarter_factor + intervention1, sample1_200,
                       svymean, vartype = "se", na.rm = TRUE) %>%
  as.data.frame() %>%
  rename(
    percentage = employed,
    se = se
  ) %>%
  mutate(
    percentage = percentage * 100,
    se = se * 100,
    lower = pmax(percentage - 1.96 * se, 0),
    upper = pmin(percentage + 1.96 * se, 100)
  ) %>%
  filter(quarter_factor != "2023 Q2")

policy_change_x <- which(levels(employed_quarter$quarter_factor) == "2023 Q2") + (1/3)

employed_quarter_plot <- ggplot(employed_quarter, aes(x = quarter_factor, y = percentage, color = intervention1, group = intervention1)) +
  geom_line() +
  geom_point() +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2) +
  geom_vline(xintercept = policy_change_x, linetype = "dashed", color = "black") +  # Policy change in July 2023
  labs(
    x = "Date",
    y = "Employment, %"
  ) +
  scale_x_discrete(labels = c("Mar 2022", "Jun 2022", "Sep 2022", "Dec 2022", 
                              "Mar 2023", "Jun 2023", "Sep 2023", "Dec 2023",
                              "Mar 2024", "Jun 2024", "Sep 2024"),
                   drop = FALSE) +
  scale_color_brewer(palette = "Set1", labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    legend.title = element_blank()
  ) +
  ylim(0, 100)

employed_quarter_plot
ggsave("employed_quarter_plot_200.jpg")
```

### GA v non-expansion >65
```{r}
# Medicaid
medicaid_quarter <- svyby(~medicaid, ~quarter_factor + intervention3, sample3_65,
                       svymean, vartype = "se", na.rm = TRUE) %>%
  as.data.frame() %>%
  rename(
    percentage = medicaid,
    se = se
  ) %>%
  mutate(
    percentage = percentage * 100,
    se = se * 100,
    lower = pmax(percentage - 1.96 * se, 0),
    upper = pmin(percentage + 1.96 * se, 100)
  ) %>%
  filter(quarter_factor != "2023 Q2")

policy_change_x <- which(levels(medicaid_quarter$quarter_factor) == "2023 Q2") + (1/3)

medicaid_quarter_plot <- ggplot(medicaid_quarter, aes(x = quarter_factor, y = percentage, color = intervention3, group = intervention3)) +
  geom_line() +
  geom_point() +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2) +
  geom_vline(xintercept = policy_change_x, linetype = "dashed", color = "black") +  # Policy change in July 2023
  labs(
    x = "Date",
    y = "Medicaid coverage, %"
  ) +
  scale_x_discrete(labels = c("Mar 2022", "Jun 2022", "Sep 2022", "Dec 2022", 
                              "Mar 2023", "Jun 2023", "Sep 2023", "Dec 2023",
                              "Mar 2024", "Jun 2024", "Sep 2024"),
                   drop = FALSE) +
  scale_color_brewer(palette = "Set1", labels = c("Non-expansion states", "Georgia")) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    legend.title = element_blank()
  ) +
  ylim(0, 100)

medicaid_quarter_plot
ggsave("medicaid_quarter_plot_south_65.jpg")

# Uninsured
uninsured_quarter <- svyby(~uninsured, ~quarter_factor + intervention3, sample3_65,
                       svymean, vartype = "se", na.rm = TRUE) %>%
  as.data.frame() %>%
  rename(
    percentage = uninsured,
    se = se
  ) %>%
  mutate(
    percentage = percentage * 100,
    se = se * 100,
    lower = pmax(percentage - 1.96 * se, 0),
    upper = pmin(percentage + 1.96 * se, 100)
  ) %>%
  filter(quarter_factor != "2023 Q2")

policy_change_x <- which(levels(uninsured_quarter$quarter_factor) == "2023 Q2") + (1/3)

uninsured_quarter_plot <- ggplot(uninsured_quarter, aes(x = quarter_factor, y = percentage, color = intervention3, group = intervention3)) +
  geom_line() +
  geom_point() +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2) +
  geom_vline(xintercept = policy_change_x, linetype = "dashed", color = "black") +  # Policy change in July 2023
  labs(
    x = "Date",
    y = "Uninsured, %"
  ) +
  scale_x_discrete(labels = c("Mar 2022", "Jun 2022", "Sep 2022", "Dec 2022", 
                              "Mar 2023", "Jun 2023", "Sep 2023", "Dec 2023",
                              "Mar 2024", "Jun 2024", "Sep 2024"),
                   drop = FALSE) +
  scale_color_brewer(palette = "Set1", labels = c("Non-expansion states", "Georgia")) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    legend.title = element_blank()
  ) +
  ylim(0, 100)

uninsured_quarter_plot
ggsave("uninsured_quarter_plot_south_65.jpg")

# Employed
employed_quarter <- svyby(~employed, ~quarter_factor + intervention3, sample3_65,
                       svymean, vartype = "se", na.rm = TRUE) %>%
  as.data.frame() %>%
  rename(
    percentage = employed,
    se = se
  ) %>%
  mutate(
    percentage = percentage * 100,
    se = se * 100,
    lower = pmax(percentage - 1.96 * se, 0),
    upper = pmin(percentage + 1.96 * se, 100)
  ) %>%
  filter(quarter_factor != "2023 Q2")

policy_change_x <- which(levels(employed_quarter$quarter_factor) == "2023 Q2") + (1/3)

employed_quarter_plot <- ggplot(employed_quarter, aes(x = quarter_factor, y = percentage, color = intervention3, group = intervention3)) +
  geom_line() +
  geom_point() +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2) +
  geom_vline(xintercept = policy_change_x, linetype = "dashed", color = "black") +  # Policy change in July 2023
  labs(
    x = "Date",
    y = "Employment, %"
  ) +
  scale_x_discrete(labels = c("Mar 2022", "Jun 2022", "Sep 2022", "Dec 2022", 
                              "Mar 2023", "Jun 2023", "Sep 2023", "Dec 2023",
                              "Mar 2024", "Jun 2024", "Sep 2024"),
                   drop = FALSE) +
  scale_color_brewer(palette = "Set1", labels = c("Non-expansion states", "Georgia")) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    legend.title = element_blank()
  ) +
  ylim(0, 100)

employed_quarter_plot
ggsave("employed_quarter_plot_south_65.jpg")
```

# Create DID table
```{r}
gen_did_tbl <- function(outcome_var, survey_design, z_value = 1.96) {
  # -------------------------------------------------------------------
  # 1) Intervention group
  # -------------------------------------------------------------------
  # Subset design for the intervention group
  int_design <- subset(survey_design, intervention1 == TRUE)

  # Calculate pre vs. post means with covariance
  # So we can do a correct difference for the intervention group
  tbl_t <- svyby(
    formula = as.formula(paste0("~", outcome_var)),
    by = ~post,               
    design = int_design,
    FUN = svymean,
    na.rm = TRUE,
    covmat = TRUE,            # <--- ensures we get the full covariance matrix
    vartype = "ci"           
  )

  # Pre (FALSE) means
  pre_mean_t       <- tbl_t[tbl_t$post == FALSE, outcome_var] * 100
  pre_ci_l_t       <- tbl_t[tbl_t$post == FALSE, "ci_l"] * 100
  pre_ci_u_t       <- tbl_t[tbl_t$post == FALSE, "ci_u"] * 100

  # Post (TRUE) means
  post_mean_t      <- tbl_t[tbl_t$post == TRUE, outcome_var] * 100
  post_ci_l_t      <- tbl_t[tbl_t$post == TRUE, "ci_l"] * 100
  post_ci_u_t      <- tbl_t[tbl_t$post == TRUE, "ci_u"] * 100

  # Use svycontrast to get the difference = Post (TRUE) - Pre (FALSE)
  diff_t <- svycontrast(
    tbl_t,
    quote(`TRUE` - `FALSE`)
  )
  # Coefficient (point estimate) is in coef(diff_t)
  diff_t_est <- coef(diff_t)[1] * 100   
  diff_t_se  <- SE(diff_t)[1]   * 100
  # 95% CI from confint()
  diff_t_ci  <- confint(diff_t) * 100  
  diff_t_ci_l <- diff_t_ci[1, 1]
  diff_t_ci_u <- diff_t_ci[1, 2]

  # Also get a p-value for (pre vs post) in the intervention group
  did_ttest_t <- svyttest(
    as.formula(paste0(outcome_var, " ~ post")),
    design = int_design
  )
  did_pval_t <- formatC(did_ttest_t$p.value, format = "f", digits = 4)


  # -------------------------------------------------------------------
  # 2) Control group
  # -------------------------------------------------------------------
  # Subset design for the control group
  ctl_design <- subset(survey_design, intervention1 == FALSE)

  # Calculate pre vs. post means with covariance
  tbl_c <- svyby(
    formula = as.formula(paste0("~", outcome_var)),
    by = ~post,               
    design = ctl_design,
    FUN = svymean,
    na.rm = TRUE,
    covmat = TRUE,
    vartype = "ci"
  )

  # Pre (FALSE)
  pre_mean_c  <- tbl_c[tbl_c$post == FALSE, outcome_var] * 100
  pre_ci_l_c  <- tbl_c[tbl_c$post == FALSE, "ci_l"] * 100
  pre_ci_u_c  <- tbl_c[tbl_c$post == FALSE, "ci_u"] * 100

  # Post (TRUE)
  post_mean_c <- tbl_c[tbl_c$post == TRUE, outcome_var] * 100
  post_ci_l_c <- tbl_c[tbl_c$post == TRUE, "ci_l"] * 100
  post_ci_u_c <- tbl_c[tbl_c$post == TRUE, "ci_u"] * 100

  # Difference in the control group
  diff_c <- svycontrast(
    tbl_c,
    quote(`TRUE` - `FALSE`)
  )
  diff_c_est <- coef(diff_c)[1] * 100
  diff_c_se  <- SE(diff_c)[1]   * 100
  diff_c_ci  <- confint(diff_c) * 100
  diff_c_ci_l <- diff_c_ci[1, 1]
  diff_c_ci_u <- diff_c_ci[1, 2]

  # p-value for control group
  did_ttest_c <- svyttest(
    as.formula(paste0(outcome_var, " ~ post")),
    design = ctl_design
  )
  did_pval_c <- formatC(did_ttest_c$p.value, format = "f", digits = 4)


  # -------------------------------------------------------------------
  # 3) Print out results
  # -------------------------------------------------------------------
  # Intervention group
  cat("Intervention group:\n")
  cat(sprintf("Pre period mean: %.1f (%.1f, %.1f)\n",
              pre_mean_t, pre_ci_l_t, pre_ci_u_t))
  cat(sprintf("Post period mean: %.1f (%.1f, %.1f)\n",
              post_mean_t, post_ci_l_t, post_ci_u_t))
  cat(sprintf("Difference: %.1f (%.1f, %.1f)\n",
              diff_t_est, diff_t_ci_l, diff_t_ci_u))
  cat(sprintf("P value: %s\n\n", did_pval_t))

  # Control group
  cat("Control group:\n")
  cat(sprintf("Pre period mean: %.1f (%.1f, %.1f)\n",
              pre_mean_c, pre_ci_l_c, pre_ci_u_c))
  cat(sprintf("Post period mean: %.1f (%.1f, %.1f)\n",
              post_mean_c, post_ci_l_c, post_ci_u_c))
  cat(sprintf("Difference: %.1f (%.1f, %.1f)\n",
              diff_c_est, diff_c_ci_l, diff_c_ci_u))
  cat(sprintf("P value: %s\n\n", did_pval_c))
}

# GA v SD 19-64
gen_did_tbl("medicaid", sample1)
gen_did_tbl("uninsured", sample1)
gen_did_tbl("employed", sample1)

# GA v SD >65
gen_did_tbl("medicaid", sample1_65)
gen_did_tbl("uninsured", sample1_65)
gen_did_tbl("employed", sample1_65)

# GA v SD >65 Medicare
gen_did_tbl("medicaid", sample1_65_medicare)
gen_did_tbl("uninsured", sample1_65_medicare)
gen_did_tbl("employed", sample1_65_medicare)

# GA v SD >70
gen_did_tbl("medicaid", sample1_70)
gen_did_tbl("uninsured", sample1_70)
gen_did_tbl("employed", sample1_70)

# GA v SD >70 Medicare
gen_did_tbl("medicaid", sample1_70_medicare)
gen_did_tbl("uninsured", sample1_70_medicare)
gen_did_tbl("employed", sample1_70_medicare)

# GA v SD >200% FPL
gen_did_tbl("medicaid", sample1_200)
gen_did_tbl("uninsured", sample1_200)
gen_did_tbl("employed", sample1_200)
```

```{r}
gen_did_tbl <- function(outcome_var, survey_design, z_value = 1.96) {
  # -------------------------------------------------------------------
  # 1) Intervention group
  # -------------------------------------------------------------------
  # Subset design for the intervention group
  int_design <- subset(survey_design, intervention3 == TRUE)

  # Calculate pre vs. post means with covariance
  # So we can do a correct difference for the intervention group
  tbl_t <- svyby(
    formula = as.formula(paste0("~", outcome_var)),
    by = ~post,               
    design = int_design,
    FUN = svymean,
    na.rm = TRUE,
    covmat = TRUE,            # <--- ensures we get the full covariance matrix
    vartype = "ci"           
  )

  # Pre (FALSE) means
  pre_mean_t       <- tbl_t[tbl_t$post == FALSE, outcome_var] * 100
  pre_ci_l_t       <- tbl_t[tbl_t$post == FALSE, "ci_l"] * 100
  pre_ci_u_t       <- tbl_t[tbl_t$post == FALSE, "ci_u"] * 100

  # Post (TRUE) means
  post_mean_t      <- tbl_t[tbl_t$post == TRUE, outcome_var] * 100
  post_ci_l_t      <- tbl_t[tbl_t$post == TRUE, "ci_l"] * 100
  post_ci_u_t      <- tbl_t[tbl_t$post == TRUE, "ci_u"] * 100

  # Use svycontrast to get the difference = Post (TRUE) - Pre (FALSE)
  diff_t <- svycontrast(
    tbl_t,
    quote(`TRUE` - `FALSE`)
  )
  # Coefficient (point estimate) is in coef(diff_t)
  diff_t_est <- coef(diff_t)[1] * 100   
  diff_t_se  <- SE(diff_t)[1]   * 100
  # 95% CI from confint()
  diff_t_ci  <- confint(diff_t) * 100  
  diff_t_ci_l <- diff_t_ci[1, 1]
  diff_t_ci_u <- diff_t_ci[1, 2]

  # Also get a p-value for (pre vs post) in the intervention group
  did_ttest_t <- svyttest(
    as.formula(paste0(outcome_var, " ~ post")),
    design = int_design
  )
  did_pval_t <- formatC(did_ttest_t$p.value, format = "f", digits = 4)


  # -------------------------------------------------------------------
  # 2) Control group
  # -------------------------------------------------------------------
  # Subset design for the control group
  ctl_design <- subset(survey_design, intervention3 == FALSE)

  # Calculate pre vs. post means with covariance
  tbl_c <- svyby(
    formula = as.formula(paste0("~", outcome_var)),
    by = ~post,               
    design = ctl_design,
    FUN = svymean,
    na.rm = TRUE,
    covmat = TRUE,
    vartype = "ci"
  )

  # Pre (FALSE)
  pre_mean_c  <- tbl_c[tbl_c$post == FALSE, outcome_var] * 100
  pre_ci_l_c  <- tbl_c[tbl_c$post == FALSE, "ci_l"] * 100
  pre_ci_u_c  <- tbl_c[tbl_c$post == FALSE, "ci_u"] * 100

  # Post (TRUE)
  post_mean_c <- tbl_c[tbl_c$post == TRUE, outcome_var] * 100
  post_ci_l_c <- tbl_c[tbl_c$post == TRUE, "ci_l"] * 100
  post_ci_u_c <- tbl_c[tbl_c$post == TRUE, "ci_u"] * 100

  # Difference in the control group
  diff_c <- svycontrast(
    tbl_c,
    quote(`TRUE` - `FALSE`)
  )
  diff_c_est <- coef(diff_c)[1] * 100
  diff_c_se  <- SE(diff_c)[1]   * 100
  diff_c_ci  <- confint(diff_c) * 100
  diff_c_ci_l <- diff_c_ci[1, 1]
  diff_c_ci_u <- diff_c_ci[1, 2]

  # p-value for control group
  did_ttest_c <- svyttest(
    as.formula(paste0(outcome_var, " ~ post")),
    design = ctl_design
  )
  did_pval_c <- formatC(did_ttest_c$p.value, format = "f", digits = 4)


  # -------------------------------------------------------------------
  # 3) Print out results
  # -------------------------------------------------------------------
  # Intervention group
  cat("Intervention group:\n")
  cat(sprintf("Pre period mean: %.1f (%.1f, %.1f)\n",
              pre_mean_t, pre_ci_l_t, pre_ci_u_t))
  cat(sprintf("Post period mean: %.1f (%.1f, %.1f)\n",
              post_mean_t, post_ci_l_t, post_ci_u_t))
  cat(sprintf("Difference: %.1f (%.1f, %.1f)\n",
              diff_t_est, diff_t_ci_l, diff_t_ci_u))
  cat(sprintf("P value: %s\n\n", did_pval_t))

  # Control group
  cat("Control group:\n")
  cat(sprintf("Pre period mean: %.1f (%.1f, %.1f)\n",
              pre_mean_c, pre_ci_l_c, pre_ci_u_c))
  cat(sprintf("Post period mean: %.1f (%.1f, %.1f)\n",
              post_mean_c, post_ci_l_c, post_ci_u_c))
  cat(sprintf("Difference: %.1f (%.1f, %.1f)\n",
              diff_c_est, diff_c_ci_l, diff_c_ci_u))
  cat(sprintf("P value: %s\n\n", did_pval_c))
}

# GA v non-expansion 19-64
gen_did_tbl("medicaid", sample3)
gen_did_tbl("uninsured", sample3)
gen_did_tbl("employed", sample3)

# GA v non-expansion >65
gen_did_tbl("medicaid", sample3_65)
gen_did_tbl("uninsured", sample3_65)
gen_did_tbl("employed", sample3_65)
```

# Calculate N's
```{r}
# Georgia vs. South Dakota
## Unweighted N in pre period
total_tbl1_pre_u <- table(sample1_pre$variables$intervention1)
total_tbl1_pre_u

## Unweighted N in post period
total_tbl1_post_u <- table(sample1_post$variables$intervention1)
total_tbl1_post_u

# Georgia vs. Alabama, Florida, Texas, Mississippi, South Carolina
## Unweighted N in pre period
total_tbl3_pre_u <- table(sample3_pre$variables$intervention3)
total_tbl3_pre_u

## Unweighted N in post period
total_tbl3_post_u <- table(sample3_post$variables$intervention3)
total_tbl3_post_u
```

# Export raw data to Stata for Michael
```{r}
write_csv(data, "georgia_data_v3.csv")

# Check data
temp <- read_csv("georgia_data_v3.csv")

table(data$post)
table(temp$post)

table(data$intervention1)
table(temp$intervention1)

table(data$intervention3)
table(temp$intervention3)

rm(temp)

sample <- data %>%
  filter(
    (intervention1 %in% c(FALSE, TRUE) | intervention2 %in% c(FALSE, TRUE) | intervention3 %in% c(FALSE, TRUE)) & # Intervention or control group
      age >= 19 & # >=19 years old
      fpg <= 100 & # Income up to 100% FPL
      not_missing_hi == TRUE & # Health insurance not missing
      not_missing_employment == TRUE # Employment not missing
  )

write.csv(sample, "georgia_data_filtered_v3.csv", row.names = FALSE)
```

# Baseline characteristics table
```{r}
# Unweighted N
total_tbl_pre_u <- table(sample1_pre$variables$intervention1)
total_tbl_pre_u

total_tbl_post_u <- table(sample1_post$variables$intervention1)
total_tbl_post_u

# Weighted N
total_tbl_pre_w <- svytable(~intervention1, design = sample1_pre) %>% as.data.frame()
total_tbl_pre_w

total_tbl_post_w <- svytable(~intervention1, design = sample1_post) %>% as.data.frame()
total_tbl_post_w

# Age
age_tbl <- svyby(~age, ~state + post, sample1, svymean, vartype = c ("se"), na.rm = TRUE)
age_tbl

age_ttest_pre <- svyttest(age~state, sample1_pre)
age_ttest_pre

age_ttest_post <- svyttest(age~state, sample1_post)
age_ttest_post

# Sex
sex_tbl <- svyby(~sex_cat, ~state + post, sample1, svymean, vartype = c("ci"), na.rm = TRUE)
sex_tbl

sex_chi_pre <- svychisq(~sex_cat + state, sample1_pre)
sex_chi_pre

sex_chi_post <- svychisq(~sex_cat + state, sample1_post)
sex_chi_post

# Race
race_tbl <- svyby(~race_cat, ~state + post, sample1, svymean, vartype = c("ci"), na.rm = TRUE)
race_tbl

race_chi_pre <- svychisq(~race_cat + state, sample1_pre)
race_chi_pre

race_chi_post <- svychisq(~race_cat + state, sample1_post)
race_chi_post

# Education
bachelor_tbl <- svyby(~bachelor_cat, ~state + post, sample1, svymean, vartype = c("ci"), na.rm = TRUE)
bachelor_tbl

bachelor_chi_pre <- svychisq(~bachelor_cat + state, sample1_pre)
bachelor_chi_pre

bachelor_chi_post <- svychisq(~bachelor_cat + state, sample1_post)
bachelor_chi_post
```

# Playground 
```{r}
# Load required libraries
library(survey)
library(srvyr)
library(dplyr)
library(ggplot2)

# Convert to srvyr object for tidy syntax
sample1_srvyr <- as_survey(sample1)

# Calculate survey-weighted proportions of age categories by intervention and year
age_cat_summary <- sample1_srvyr %>%
  group_by(intervention1, year, age_cat) %>%
  summarize(prop = survey_mean(vartype = "ci", proportion = TRUE), .groups = "drop")

# Plot the bar graph
ggplot(age_cat_summary, aes(x = age_cat, y = prop, fill = intervention1)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_wrap(~ year) +
  labs(x = "Age Category", y = "Proportion", fill = "Intervention",
       title = "Age Categories by Intervention and Year (Survey-Weighted)") +
  theme_minimal()

# Calculate survey-weighted proportions of sex categories by intervention and year
sex_cat_summary <- sample1_srvyr %>%
  group_by(intervention1, year, sex_cat) %>%
  summarize(prop = survey_mean(vartype = "ci", proportion = TRUE), .groups = "drop")

# Plot the bar graph
ggplot(sex_cat_summary, aes(x = sex_cat, y = prop, fill = intervention1)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_wrap(~ year) +
  labs(x = "Sex Category", y = "Proportion", fill = "Intervention",
       title = "Sex Categories by Intervention and Year (Survey-Weighted)") +
  theme_minimal()


# Convert to srvyr object for tidy syntax
sample3_srvyr <- as_survey(sample3)

# Calculate survey-weighted proportions of age categories by intervention and year
age_cat_summary <- sample3_srvyr %>%
  group_by(intervention3, year, age_cat) %>%
  summarize(prop = survey_mean(vartype = "ci", proportion = TRUE), .groups = "drop")

# Plot the bar graph
ggplot(age_cat_summary, aes(x = age_cat, y = prop, fill = intervention3)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_wrap(~ year) +
  labs(x = "Age Category", y = "Proportion", fill = "Intervention",
       title = "Age Categories by Intervention and Year (Survey-Weighted)") +
  theme_minimal()

# Calculate survey-weighted proportions of sex categories by intervention and year
sex_cat_summary <- sample3_srvyr %>%
  group_by(intervention3, year, sex_cat) %>%
  summarize(prop = survey_mean(vartype = "ci", proportion = TRUE), .groups = "drop")

# Plot the bar graph
ggplot(sex_cat_summary, aes(x = sex_cat, y = prop, fill = intervention3)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_wrap(~ year) +
  labs(x = "Sex Category", y = "Proportion", fill = "Intervention",
       title = "Sex Categories by Intervention and Year (Survey-Weighted)") +
  theme_minimal()

# Compare results to different weighting
sample_raw <- data %>%
 mutate(
   intervention1 = case_when(
     state == "Georgia" ~ TRUE,
     state == "South Dakota" ~ FALSE,
     TRUE ~ NA
   ),
   intervention3 = case_when(
     state == "Georgia" ~ TRUE,
     state %in% c("Alabama", "Florida", "Texas", "Mississippi", "South Carolina") ~ FALSE, 
     TRUE ~ NA
   ),
   intervention4 = case_when(
     state == "Georgia" ~ TRUE,
     state %in% c("Tennessee") ~ FALSE,
     TRUE ~ NA
   ),
   post = case_when( 
      # Blank out March 29, 2023 to July 10, 2023
      date < ymd("2023-03-29") ~ FALSE,
      # date < ymd("2023-07-10") ~ FALSE,
      date > ymd("2023-07-10") ~ TRUE,
      # date > ymd("2024-03-31") ~ TRUE,
      TRUE ~ NA
    )
 ) %>%
 filter(
   (intervention1 %in% c(FALSE, TRUE) | intervention3 %in% c(FALSE, TRUE)) & # Intervention or control group
     age >= 19 & age <= 64 & # 19-64 years old
     # age >= 70 & # 65+ years old
     # fpg >= 200 & # Income up to 100% FPL
     not_missing_hi == TRUE & # Health insurance not missing
     not_missing_employment == TRUE # Employment not missing
 ) %>%
 mutate(
   state_factor = as.factor(state),
   date_factor = as.factor(date),
  race_cat = case_when(
     RRACE == 1 ~ "White",
     RRACE == 2 ~ "Black",
     RRACE == 3 ~ "Asian",
     RRACE == 4 ~ "Other",
     TRUE ~ NA_character_
   ),
   race_cat = case_when( # Note: Hispanic ethnicity overrides all other race variables
     RHISPANIC == 1 ~ race_cat,
     RHISPANIC == 2 ~ "Hispanic",
     TRUE ~ race_cat
   ),
   edu_cat = case_when(
     EEDUC == 1 ~ "Less than high school",
     EEDUC == 2 ~ "Some high school",
     EEDUC == 3 ~ "High school graduate",
     EEDUC == 4 ~ "Some college",
     EEDUC == 5 ~ "Associates degree",
     EEDUC == 6 ~ "Bachelors degree",
     EEDUC == 7 ~ "Graduate degree",
     TRUE ~ NA_character_
   ),
  inc_cat = case_when(
     fpg <= 100 ~ "Low income",
     fpg >= 200 ~ "High income"
  )
 )

sample_raw_pre <- sample_raw %>%
 filter(
   post == 0
 )

library(sandwich)
library(lmtest)

# Parallel trends
## Medicaid
medicaid_pttest <- lm(medicaid ~ intervention1 * date + state_factor + date_factor, data = sample_raw_pre, weights = PWEIGHT_divided)
summary(medicaid_pttest)
# medicaid_pttest_se <- vcovCL(medicaid_pttest, cluster = ~ state_factor)
# medicaid_pttest_coef <- coeftest(medicaid_pttest, vcov = medicaid_pttest_se)
# medicaid_pttest_coef
# confint(medicaid_pttest_coef)

## Uninsured
uninsured_pttest <- lm(uninsured ~ intervention1 * date + state_factor + date_factor, data = sample_raw_pre, weights = PWEIGHT_divided)
summary(uninsured_pttest)
# uninsured_pttest_se <- vcovCL(uninsured_pttest, cluster = ~ state_factor)
# uninsured_pttest_coef <- coeftest(uninsured_pttest, vcov = uninsured_pttest_se)
# uninsured_pttest_coef
# confint(uninsured_pttest_coef)

## Employed
employed_pttest <- lm(employed ~ intervention1 * date + state_factor + date_factor, data = sample_raw_pre, weights = PWEIGHT_divided)
summary(employed_pttest)
# employed_pttest_se <- vcovCL(employed_pttest, cluster = ~ state_factor)
# employed_pttest_coef <- coeftest(employed_pttest, vcov = employed_pttest_se)
# employed_pttest_coef
# confint(employed_pttest_coef)

# non-expansion states
## Medicaid
medicaid_pttest <- lm(medicaid ~ intervention3 * date + state_factor + date_factor, data = sample_raw_pre, weights = PWEIGHT_divided)
summary(medicaid_pttest)
# medicaid_pttest_se <- vcovCL(medicaid_pttest, cluster = ~ state_factor)
# medicaid_pttest_coef <- coeftest(medicaid_pttest, vcov = medicaid_pttest_se)
# medicaid_pttest_coef
# confint(medicaid_pttest_coef)

## Uninsured
uninsured_pttest <- lm(uninsured ~ intervention3 * date + state_factor + date_factor, data = sample_raw_pre, weights = PWEIGHT_divided)
summary(uninsured_pttest)
uninsured_pttest_se <- vcovCL(uninsured_pttest, cluster = ~ state_factor)
uninsured_pttest_coef <- coeftest(uninsured_pttest, vcov = uninsured_pttest_se)
uninsured_pttest_coef
confint(uninsured_pttest_coef)

## Employed
employed_pttest <- lm(employed ~ intervention3 * date + state_factor + date_factor, data = sample_raw_pre, weights = PWEIGHT_divided)
summary(employed_pttest)
employed_pttest_se <- vcovCL(employed_pttest, cluster = ~ state_factor)
employed_pttest_coef <- coeftest(employed_pttest, vcov = employed_pttest_se)
employed_pttest_coef
confint(employed_pttest_coef)

## Unadjusted DID
# # Medicaid
medicaid_unadj <- lm(medicaid ~ intervention3 * post + state_factor + date_factor, data = sample_raw, weights = PWEIGHT_divided)
summary(medicaid_unadj)
medicaid_unadj_se <- vcovCL(medicaid_unadj, cluster = ~ state_factor)
medicaid_unadj_coef <- coeftest(medicaid_unadj, vcov = medicaid_unadj_se)
medicaid_unadj_coef
confint(medicaid_unadj_coef)
# 
# # Uninsured
# uninsured_unadj <- lm(uninsured ~ intervention * post + state_factor + date_factor, data = sample_raw, weights = PWEIGHT_divided)
# uninsured_unadj_se <- vcovCL(uninsured_unadj, cluster = ~ state_factor)
# uninsured_unadj_coef <- coeftest(uninsured_unadj, vcov = uninsured_unadj_se)
# uninsured_unadj_coef
# confint(uninsured_unadj_coef)
# 
# # Employed
# employed_unadj <- lm(employed ~ intervention * post + state_factor + date_factor, data = sample_raw, weights = PWEIGHT_divided)
# employed_unadj_se <- vcovCL(employed_unadj, cluster = ~ state_factor)
# employed_unadj_coef <- coeftest(employed_unadj, vcov = employed_unadj_se)
# employed_unadj_coef
# confint(employed_unadj_coef)

## Adjusted DID
# Medicaid
medicaid_adj <- lm(medicaid ~ intervention1 * post * inc_cat + age_cat + sex_cat + race_cat + date_factor, data = sample_raw, weights = PWEIGHT_divided)
summary(medicaid_adj)

# Uninsured
uninsured_adj <- lm(uninsured ~ intervention1 * post * inc_cat + age_cat + sex_cat + race_cat + date_factor, data = sample_raw, weights = PWEIGHT_divided)
summary(uninsured_adj)

# Employed
employed_adj <- lm(employed ~ intervention1 * post * inc_cat + age_cat + sex_cat + race_cat + date_factor, data = sample_raw, weights = PWEIGHT_divided)
summary(employed_adj)

# Non-expansion states
# Medicaid
medicaid_adj <- lm(medicaid ~ intervention3 * post + age_cat + sex_cat + race_cat + state_factor + date_factor, data = sample_raw, weights = PWEIGHT_divided)
summary(medicaid_adj)
# medicaid_adj_se <- vcovCL(medicaid_adj, cluster = ~ state_factor)
# medicaid_adj_coef <- coeftest(medicaid_adj, vcov = medicaid_adj_se)
# medicaid_adj_coef
# confint(medicaid_adj_coef)

# Uninsured
uninsured_adj <- lm(uninsured ~ intervention3 * post + age_cat + sex_cat + race_cat + state_factor + date_factor, data = sample_raw, weights = PWEIGHT_divided)
summary(uninsured_adj)
# uninsured_adj_se <- vcovCL(uninsured_adj, cluster = ~ state_factor)
# uninsured_adj_coef <- coeftest(uninsured_adj, vcov = uninsured_adj_se)
# uninsured_adj_coef
# confint(uninsured_adj_coef)

# Employed
employed_adj <- lm(employed ~ intervention3 * post + age_cat + sex_cat + race_cat + state_factor + date_factor, data = sample_raw, weights = PWEIGHT_divided)
summary(employed_adj)
# employed_adj_se <- vcovCL(employed_adj, cluster = ~ state_factor)
# employed_adj_coef <- coeftest(employed_adj, vcov = employed_adj_se)
# employed_adj_coef
# confint(employed_adj_coef)
```
