---
title: "Georgia Medicaid Work Requirements"
output: html_document
date: "2024-09-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load libraries

```{r libraries}
library(tidyverse)
library(haven)
library(summarytools)
library(survey)
```

## Load data

```{r}
# Load the datasets
llcp2021 <- read_xpt("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/BRFSS/Data/LLCP2021.XPT")
llcp2022 <- read_xpt("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/BRFSS/Data/LLCP2022.XPT")
llcp2023 <- read_xpt("C:/Users/djohns44/OneDrive - Beth Israel Lahey Health/BRFSS/Data/LLCP2023.XPT")
```

# Clean BRFSS 2021
```{r}
# Federal Poverty 2021 calculations
llcp2021 <- llcp2021 %>%
  mutate(
    hhadult_clean = ifelse(HHADULT %in% c(77, 99), NA, HHADULT),
    children_clean = ifelse(CHILDREN == 99, NA, ifelse(CHILDREN == 88, 0, CHILDREN)),
    hh_size = ifelse(is.na(NUMADULT), 1, NUMADULT) + ifelse(is.na(hhadult_clean), 0, hhadult_clean) + ifelse(is.na(children_clean), 0, children_clean),
    hh_size = ifelse(hh_size == 0 | hh_size > 9, 1, hh_size), # Exclude 0 or >99th percentile (9)
    income_num = case_when(
      INCOME3 == 1 ~ 5000,
      INCOME3 == 2 ~ 12500,
      INCOME3 == 3 ~ 17500,
      INCOME3 == 4 ~ 22500,
      INCOME3 == 5 ~ 30000,
      INCOME3 == 6 ~ 42500,
      INCOME3 == 7 ~ 62500,
      INCOME3 == 8 ~ 87500,
      INCOME3 == 9 ~ 125000,
      INCOME3 == 10 ~ 175000,
      INCOME3 == 11 ~ 200000,
      TRUE ~ NA_real_
    ),
    fpg = case_when(
      `_STATE` != 2 & `_STATE` != 15 & hh_size == 1 ~ 100 * (income_num / 12880),
      `_STATE` != 2 & `_STATE` != 15 & hh_size == 2 ~ 100 * (income_num / 17420),
      `_STATE` != 2 & `_STATE` != 15 & hh_size == 3 ~ 100 * (income_num / 21960),
      `_STATE` != 2 & `_STATE` != 15 & hh_size == 4 ~ 100 * (income_num / 26500),
      `_STATE` != 2 & `_STATE` != 15 & hh_size == 5 ~ 100 * (income_num / 31040),
      `_STATE` != 2 & `_STATE` != 15 & hh_size == 6 ~ 100 * (income_num / 35580),
      `_STATE` != 2 & `_STATE` != 15 & hh_size == 7 ~ 100 * (income_num / 40120),
      `_STATE` != 2 & `_STATE` != 15 & hh_size >= 8 ~ 100 * (income_num / (44660 + (hh_size - 8) * 4540)),
      `_STATE` == 2 & hh_size == 1 ~ 100 * (income_num / 16090),
      `_STATE` == 2 & hh_size == 2 ~ 100 * (income_num / 21770),
      `_STATE` == 2 & hh_size == 3 ~ 100 * (income_num / 27450),
      `_STATE` == 2 & hh_size == 4 ~ 100 * (income_num / 33130),
      `_STATE` == 2 & hh_size == 5 ~ 100 * (income_num / 38810),
      `_STATE` == 2 & hh_size == 6 ~ 100 * (income_num / 44490),
      `_STATE` == 2 & hh_size == 7 ~ 100 * (income_num / 50170),
      `_STATE` == 2 & hh_size >= 8 ~ 100 * (income_num / (55850 + (hh_size - 8) * 5680)),
      `_STATE` == 15 & hh_size == 1 ~ 100 * (income_num / 14820),
      `_STATE` == 15 & hh_size == 2 ~ 100 * (income_num / 20040),
      `_STATE` == 15 & hh_size == 3 ~ 100 * (income_num / 25260),
      `_STATE` == 15 & hh_size == 4 ~ 100 * (income_num / 30480),
      `_STATE` == 15 & hh_size == 5 ~ 100 * (income_num / 35700),
      `_STATE` == 15 & hh_size == 6 ~ 100 * (income_num / 40920),
      `_STATE` == 15 & hh_size == 7 ~ 100 * (income_num / 46140),
      `_STATE` == 15 & hh_size >= 8 ~ 100 * (income_num / (51360 + (hh_size - 8) * 5220)),
      TRUE ~ NA_real_
    ),
    age = `_AGE80`,
    age_cat = case_when(
      `_AGE80` >= 18 & `_AGE80` <= 24 ~ "18-24",
      `_AGE80` >= 25 & `_AGE80` <= 34 ~ "25-34",
      `_AGE80` >= 35 & `_AGE80` <= 44 ~ "35-44",
      `_AGE80` >= 45 & `_AGE80` <= 54 ~ "45-54",
      `_AGE80` >= 55 & `_AGE80` <= 64 ~ "55-64",
      `_AGE80` >= 65 ~ ">65",
      TRUE ~ NA_character_
    ),
    sex_cat = case_when(
      SEXVAR == 1 ~ "1.Male",
      SEXVAR == 2 ~ "2.Female",
      TRUE ~ NA_character_
    ),
    race_cat = case_when(
      `_IMPRACE` == 1 ~ "1.Non-Hispanic White",
      `_IMPRACE` == 2 ~ "2.Non-Hispanic Black",
      `_IMPRACE` == 3 ~ "3.Non-Hispanic Asian",
      `_IMPRACE` == 5 ~ "4.Hispanic",
      `_IMPRACE` %in% c(4, 6) ~ "5.Other",
      TRUE ~ NA_character_
    ),
    education_cat = case_when(
      EDUCA %in% c(5, 6) ~ "College educated",
      EDUCA %in% c(1, 2, 3, 4) ~ "Not college educated",
      TRUE ~ NA_character_
    ),
    medicaid = ifelse(PRIMINSR == 5, 1, 0),
    esi = ifelse(PRIMINSR == 1, 1, 0),
    uninsured = ifelse(`_HLTHPLN` == 2, 1, ifelse(`_HLTHPLN` == 1, 0, NA)),
    employed = ifelse(EMPLOY1 %in% c(1, 2), 1, 0),
    student = ifelse(EMPLOY1 == 6, 1, 0),
    qualifying = ifelse(EMPLOY1 %in% c(1, 2, 6), 1, 0),
    pcp = ifelse(PERSDOC3 %in% c(1, 2), 1, ifelse(PERSDOC3 == 3, 0, NA)),
    not_afford = ifelse(MEDCOST1 == 1, 1, ifelse(MEDCOST1 == 2, 0, NA)),
    dm = ifelse(DIABETE4 == 1, 1, ifelse(DIABETE4 %in% c(2, 3, 4), 0, NA)),
    mi = ifelse(CVDINFR4 == 1, 1, ifelse(CVDINFR4 == 2, 0, NA)),
    chd = ifelse(CVDCRHD4 == 1, 1, ifelse(CVDCRHD4 == 2, 0, NA)),
    stroke = ifelse(CVDSTRK3 == 1, 1, ifelse(CVDSTRK3 == 2, 0, NA)),
    copd = ifelse(CHCCOPD3 == 1, 1, ifelse(CHCCOPD3 == 2, 0, NA)),
    # cancer = ifelse(CHCOCNCR == 1, 1, ifelse(CHCOCNCR == 2, 0, NA)),
    unemployed = ifelse(EMPLOY1 %in% c(3, 4), 1, 0)
  )
```

# Clean BRFSS 2022
```{r}
# Federal Poverty 2022 calculations
llcp2022 <- llcp2022 %>%
  mutate(
    hhadult_clean = ifelse(HHADULT %in% c(77, 99), NA, HHADULT),
    children_clean = ifelse(CHILDREN == 99, NA, ifelse(CHILDREN == 88, 0, CHILDREN)),
    hh_size = ifelse(is.na(NUMADULT), 1, NUMADULT) + ifelse(is.na(hhadult_clean), 0, hhadult_clean) + ifelse(is.na(children_clean), 0, children_clean),
    hh_size = ifelse(hh_size == 0 | hh_size > 9, 1, hh_size), # Exclude 0 or >99th percentile (9)
    income_num = case_when(
      INCOME3 == 1 ~ 5000,
      INCOME3 == 2 ~ 12500,
      INCOME3 == 3 ~ 17500,
      INCOME3 == 4 ~ 22500,
      INCOME3 == 5 ~ 30000,
      INCOME3 == 6 ~ 42500,
      INCOME3 == 7 ~ 62500,
      INCOME3 == 8 ~ 87500,
      INCOME3 == 9 ~ 125000,
      INCOME3 == 10 ~ 175000,
      INCOME3 == 11 ~ 200000,
      TRUE ~ NA_real_
    ),
    fpg = case_when(
      `_STATE` != 2 & `_STATE` != 15 & hh_size == 1 ~ 100 * (income_num / 13590),
      `_STATE` != 2 & `_STATE` != 15 & hh_size == 2 ~ 100 * (income_num / 18310),
      `_STATE` != 2 & `_STATE` != 15 & hh_size == 3 ~ 100 * (income_num / 23030),
      `_STATE` != 2 & `_STATE` != 15 & hh_size == 4 ~ 100 * (income_num / 27750),
      `_STATE` != 2 & `_STATE` != 15 & hh_size == 5 ~ 100 * (income_num / 32470),
      `_STATE` != 2 & `_STATE` != 15 & hh_size == 6 ~ 100 * (income_num / 37190),
      `_STATE` != 2 & `_STATE` != 15 & hh_size == 7 ~ 100 * (income_num / 41910),
      `_STATE` != 2 & `_STATE` != 15 & hh_size >= 8 ~ 100 * (income_num / (46630 + (hh_size - 8) * 4720)),
      `_STATE` == 2 & hh_size == 1 ~ 100 * (income_num / 16990),
      `_STATE` == 2 & hh_size == 2 ~ 100 * (income_num / 22890),
      `_STATE` == 2 & hh_size == 3 ~ 100 * (income_num / 28790),
      `_STATE` == 2 & hh_size == 4 ~ 100 * (income_num / 34690),
      `_STATE` == 2 & hh_size == 5 ~ 100 * (income_num / 40590),
      `_STATE` == 2 & hh_size == 6 ~ 100 * (income_num / 46490),
      `_STATE` == 2 & hh_size == 7 ~ 100 * (income_num / 52390),
      `_STATE` == 2 & hh_size >= 8 ~ 100 * (income_num / (58290 + (hh_size - 8) * 5900)),
      `_STATE` == 15 & hh_size == 1 ~ 100 * (income_num / 15630),
      `_STATE` == 15 & hh_size == 2 ~ 100 * (income_num / 21060),
      `_STATE` == 15 & hh_size == 3 ~ 100 * (income_num / 26490),
      `_STATE` == 15 & hh_size == 4 ~ 100 * (income_num / 31920),
      `_STATE` == 15 & hh_size == 5 ~ 100 * (income_num / 37350),
      `_STATE` == 15 & hh_size == 6 ~ 100 * (income_num / 42780),
      `_STATE` == 15 & hh_size == 7 ~ 100 * (income_num / 48210),
      `_STATE` == 15 & hh_size >= 8 ~ 100 * (income_num / (53640 + (hh_size - 8) * 5430)),
      TRUE ~ NA_real_
    ),
    age = `_AGE80`,
    age_cat = case_when(
      `_AGE80` >= 18 & `_AGE80` <= 24 ~ "18-24",
      `_AGE80` >= 25 & `_AGE80` <= 34 ~ "25-34",
      `_AGE80` >= 35 & `_AGE80` <= 44 ~ "35-44",
      `_AGE80` >= 45 & `_AGE80` <= 54 ~ "45-54",
      `_AGE80` >= 55 & `_AGE80` <= 64 ~ "55-64",
      `_AGE80` >= 65 ~ ">65",
      TRUE ~ NA_character_
    ),
    sex_cat = case_when(
      SEXVAR == 1 ~ "1.Male",
      SEXVAR == 2 ~ "2.Female",
      TRUE ~ NA_character_
    ),
    race_cat = case_when(
      `_IMPRACE` == 1 ~ "1.Non-Hispanic White",
      `_IMPRACE` == 2 ~ "2.Non-Hispanic Black",
      `_IMPRACE` == 3 ~ "3.Non-Hispanic Asian",
      `_IMPRACE` == 5 ~ "4.Hispanic",
      `_IMPRACE` %in% c(4, 6) ~ "5.Other",
      TRUE ~ NA_character_
    ),
    education_cat = case_when(
      EDUCA %in% c(5, 6) ~ "College educated",
      EDUCA %in% c(1, 2, 3, 4) ~ "Not college educated",
      TRUE ~ NA_character_
    ),
    medicaid = ifelse(PRIMINSR == 5, 1, 0),
    esi = ifelse(PRIMINSR == 1, 1, 0),
    uninsured = ifelse(`_HLTHPLN` == 2, 1, ifelse(`_HLTHPLN` == 1, 0, NA)),
    employed = ifelse(EMPLOY1 %in% c(1, 2), 1, 0),
    student = ifelse(EMPLOY1 == 6, 1, 0),
    qualifying = ifelse(EMPLOY1 %in% c(1, 2, 6), 1, 0),
    pcp = ifelse(PERSDOC3 %in% c(1, 2), 1, ifelse(PERSDOC3 == 3, 0, NA)),
    not_afford = ifelse(MEDCOST1 == 1, 1, ifelse(MEDCOST1 == 2, 0, NA)),
    dm = ifelse(DIABETE4 == 1, 1, ifelse(DIABETE4 %in% c(2, 3, 4), 0, NA)),
    mi = ifelse(CVDINFR4 == 1, 1, ifelse(CVDINFR4 == 2, 0, NA)),
    chd = ifelse(CVDCRHD4 == 1, 1, ifelse(CVDCRHD4 == 2, 0, NA)),
    stroke = ifelse(CVDSTRK3 == 1, 1, ifelse(CVDSTRK3 == 2, 0, NA)),
    copd = ifelse(CHCCOPD3 == 1, 1, ifelse(CHCCOPD3 == 2, 0, NA)),
    cancer = ifelse(CHCOCNC1 == 1, 1, ifelse(CHCOCNC1 == 2, 0, NA)),
    unemployed = ifelse(EMPLOY1 %in% c(3, 4), 1, 0)
  )
```

# Clean BRFSS 2023
```{r}
# Federal Poverty 2023 calculations
llcp2023 <- llcp2023 %>%
  mutate(
    hhadult_clean = ifelse(HHADULT %in% c(77, 99), NA, HHADULT),
    children_clean = ifelse(CHILDREN == 99, NA, ifelse(CHILDREN == 88, 0, CHILDREN)),
    hh_size = ifelse(is.na(NUMADULT), 1, NUMADULT) + ifelse(is.na(hhadult_clean), 0, hhadult_clean) + ifelse(is.na(children_clean), 0, children_clean),
    hh_size = ifelse(hh_size == 0 | hh_size > 9, 1, hh_size), # Exclude 0 or >99th percentile (9)
    income_num = case_when(
      INCOME3 == 1 ~ 5000,
      INCOME3 == 2 ~ 12500,
      INCOME3 == 3 ~ 17500,
      INCOME3 == 4 ~ 22500,
      INCOME3 == 5 ~ 30000,
      INCOME3 == 6 ~ 42500,
      INCOME3 == 7 ~ 62500,
      INCOME3 == 8 ~ 87500,
      INCOME3 == 9 ~ 125000,
      INCOME3 == 10 ~ 175000,
      INCOME3 == 11 ~ 200000,
      TRUE ~ NA_real_
    ),
    fpg = case_when(
      `_STATE` != 2 & `_STATE` != 15 & hh_size == 1 ~ 100 * (income_num / 14580),
      `_STATE` != 2 & `_STATE` != 15 & hh_size == 2 ~ 100 * (income_num / 19720),
      `_STATE` != 2 & `_STATE` != 15 & hh_size == 3 ~ 100 * (income_num / 24860),
      `_STATE` != 2 & `_STATE` != 15 & hh_size == 4 ~ 100 * (income_num / 30000),
      `_STATE` != 2 & `_STATE` != 15 & hh_size == 5 ~ 100 * (income_num / 35140),
      `_STATE` != 2 & `_STATE` != 15 & hh_size == 6 ~ 100 * (income_num / 40280),
      `_STATE` != 2 & `_STATE` != 15 & hh_size == 7 ~ 100 * (income_num / 45420),
      `_STATE` != 2 & `_STATE` != 15 & hh_size >= 8 ~ 100 * (income_num / (50560 + (hh_size - 8) * 5140)),
      `_STATE` == 2 & hh_size == 1 ~ 100 * (income_num / 18210),
      `_STATE` == 2 & hh_size == 2 ~ 100 * (income_num / 24640),
      `_STATE` == 2 & hh_size == 3 ~ 100 * (income_num / 31070),
      `_STATE` == 2 & hh_size == 4 ~ 100 * (income_num / 37500),
      `_STATE` == 2 & hh_size == 5 ~ 100 * (income_num / 43930),
      `_STATE` == 2 & hh_size == 6 ~ 100 * (income_num / 50360),
      `_STATE` == 2 & hh_size == 7 ~ 100 * (income_num / 56790),
      `_STATE` == 2 & hh_size >= 8 ~ 100 * (income_num / (63220 + (hh_size - 8) * 6430)),
      `_STATE` == 15 & hh_size == 1 ~ 100 * (income_num / 16770),
      `_STATE` == 15 & hh_size == 2 ~ 100 * (income_num / 22680),
      `_STATE` == 15 & hh_size == 3 ~ 100 * (income_num / 28590),
      `_STATE` == 15 & hh_size == 4 ~ 100 * (income_num / 34500),
      `_STATE` == 15 & hh_size == 5 ~ 100 * (income_num / 40410),
      `_STATE` == 15 & hh_size == 6 ~ 100 * (income_num / 46320),
      `_STATE` == 15 & hh_size == 7 ~ 100 * (income_num / 52230),
      `_STATE` == 15 & hh_size >= 8 ~ 100 * (income_num / (58140 + (hh_size - 8) * 5910)),
      TRUE ~ NA_real_
    ),
    age = `_AGE80`,
    age_cat = case_when(
      `_AGE80` >= 18 & `_AGE80` <= 24 ~ "18-24",
      `_AGE80` >= 25 & `_AGE80` <= 34 ~ "25-34",
      `_AGE80` >= 35 & `_AGE80` <= 44 ~ "35-44",
      `_AGE80` >= 45 & `_AGE80` <= 54 ~ "45-54",
      `_AGE80` >= 55 & `_AGE80` <= 64 ~ "55-64",
      `_AGE80` >= 65 ~ ">65",
      TRUE ~ NA_character_
    ),
    sex_cat = case_when(
      SEXVAR == 1 ~ "1.Male",
      SEXVAR == 2 ~ "2.Female",
      TRUE ~ NA_character_
    ),
    race_cat = case_when(
      `_IMPRACE` == 1 ~ "1.Non-Hispanic White",
      `_IMPRACE` == 2 ~ "2.Non-Hispanic Black",
      `_IMPRACE` == 3 ~ "3.Non-Hispanic Asian",
      `_IMPRACE` == 5 ~ "4.Hispanic",
      `_IMPRACE` %in% c(4, 6) ~ "5.Other",
      TRUE ~ NA_character_
    ),
    education_cat = case_when(
      EDUCA %in% c(5, 6) ~ "College educated",
      EDUCA %in% c(1, 2, 3, 4) ~ "Not college educated",
      TRUE ~ NA_character_
    ),
    medicaid = ifelse(PRIMINS1 == 5, 1, 0),
    esi = ifelse(PRIMINS1 == 1, 1, 0),
    uninsured = ifelse(`_HLTHPL1` == 2, 1, ifelse(`_HLTHPL1` == 1, 0, NA)),
    employed = ifelse(EMPLOY1 %in% c(1, 2), 1, 0),
    student = ifelse(EMPLOY1 == 6, 1, 0),
    qualifying = ifelse(EMPLOY1 %in% c(1, 2, 6), 1, 0),
    pcp = ifelse(PERSDOC3 %in% c(1, 2), 1, ifelse(PERSDOC3 == 3, 0, NA)),
    not_afford = ifelse(MEDCOST1 == 1, 1, ifelse(MEDCOST1 == 2, 0, NA)),
    dm = ifelse(DIABETE4 == 1, 1, ifelse(DIABETE4 %in% c(2, 3, 4), 0, NA)),
    mi = ifelse(CVDINFR4 == 1, 1, ifelse(CVDINFR4 == 2, 0, NA)),
    chd = ifelse(CVDCRHD4 == 1, 1, ifelse(CVDCRHD4 == 2, 0, NA)),
    stroke = ifelse(CVDSTRK3 == 1, 1, ifelse(CVDSTRK3 == 2, 0, NA)),
    copd = ifelse(CHCCOPD3 == 1, 1, ifelse(CHCCOPD3 == 2, 0, NA)),
    cancer = ifelse(CHCOCNC1 == 1, 1, ifelse(CHCOCNC1 == 2, 0, NA)),
    htn = ifelse(BPHIGH6 == 1, 1, ifelse(BPHIGH6 %in% c(2, 3, 4), 0, NA)),
    hld = ifelse(TOLDHI3 == 1, 1, ifelse(TOLDHI3 == 2, 0, NA)),
    unemployed = ifelse(EMPLOY1 %in% c(3, 4), 1, 0)
  )
```

# Merge data
```{r}
# Merge datasets
merge_2123 <- bind_rows(llcp2021, llcp2022, llcp2023)
```

# Clean merged data
```{r}
merge_2123 <- merge_2123 %>%
  mutate(
    quarter = case_when(
      IYEAR == 2021 & IMONTH %in% c("01", "02", "03") ~ "2021 Q1",
      IYEAR == 2021 & IMONTH %in% c("04", "05", "06") ~ "2021 Q2",
      IYEAR == 2021 & IMONTH %in% c("07", "08", "09") ~ "2021 Q3",
      IYEAR == 2021 & IMONTH %in% c("10", "11", "12") ~ "2021 Q4",
      IYEAR == 2022 & IMONTH %in% c("01", "02", "03") ~ "2022 Q1",
      IYEAR == 2022 & IMONTH %in% c("04", "05", "06") ~ "2022 Q2",
      IYEAR == 2022 & IMONTH %in% c("07", "08", "09") ~ "2022 Q3",
      IYEAR == 2022 & IMONTH %in% c("10", "11", "12") ~ "2022 Q4",
      IYEAR == 2023 & IMONTH %in% c("01", "02", "03") ~ "2023 Q1",
      IYEAR == 2023 & IMONTH %in% c("04", "05", "06") ~ "2023 Q2",
      IYEAR == 2023 & IMONTH %in% c("07", "08", "09") ~ "2023 Q3",
      IYEAR == 2023 & IMONTH %in% c("10", "11", "12") ~ "2023 Q4",
      TRUE ~ NA_character_
    ),
    half = case_when(
      IYEAR == 2021 & IMONTH %in% c("01", "02", "03", "04", "05", "06") ~ "2021 H1",
      IYEAR == 2021 & IMONTH %in% c("07", "08", "09", "10", "11", "12") ~ "2021 H2",
      IYEAR == 2022 & IMONTH %in% c("01", "02", "03", "04", "05", "06") ~ "2022 H1",
      IYEAR == 2022 & IMONTH %in% c("07", "08", "09", "10", "11", "12") ~ "2022 H2",
      IYEAR == 2023 & IMONTH %in% c("01", "02", "03", "04", "05", "06") ~ "2023 H1",
      IYEAR == 2023 & IMONTH %in% c("07", "08", "09", "10", "11", "12") ~ "2023 H2",
      TRUE ~ NA_character_
    ),
    state = case_when(
      `_STATE` == 1 ~ "Alabama",
      `_STATE` == 2 ~ "Alaska",
      `_STATE` == 4 ~ "Arizona",
      `_STATE` == 5 ~ "Arkansas",
      `_STATE` == 6 ~ "California",
      `_STATE` == 8 ~ "Colorado",
      `_STATE` == 9 ~ "Connecticut",
      `_STATE` == 10 ~ "Delaware",
      `_STATE` == 11 ~ "District of Columbia",
      `_STATE` == 12 ~ "Florida",
      `_STATE` == 13 ~ "Georgia",
      `_STATE` == 15 ~ "Hawaii",
      `_STATE` == 16 ~ "Idaho",
      `_STATE` == 17 ~ "Illinois",
      `_STATE` == 18 ~ "Indiana",
      `_STATE` == 19 ~ "Iowa",
      `_STATE` == 20 ~ "Kansas",
      `_STATE` == 21 ~ "Kentucky",
      `_STATE` == 22 ~ "Louisiana",
      `_STATE` == 23 ~ "Maine",
      `_STATE` == 24 ~ "Maryland",
      `_STATE` == 25 ~ "Massachusetts",
      `_STATE` == 26 ~ "Michigan",
      `_STATE` == 27 ~ "Minnesota",
      `_STATE` == 28 ~ "Mississippi",
      `_STATE` == 29 ~ "Missouri",
      `_STATE` == 30 ~ "Montana",
      `_STATE` == 31 ~ "Nebraska",
      `_STATE` == 32 ~ "Nevada",
      `_STATE` == 33 ~ "New Hampshire",
      `_STATE` == 34 ~ "New Jersey",
      `_STATE` == 35 ~ "New Mexico",
      `_STATE` == 36 ~ "New York",
      `_STATE` == 37 ~ "North Carolina",
      `_STATE` == 38 ~ "North Dakota",
      `_STATE` == 39 ~ "Ohio",
      `_STATE` == 40 ~ "Oklahoma",
      `_STATE` == 41 ~ "Oregon",
      `_STATE` == 42 ~ "Pennsylvania",
      `_STATE` == 44 ~ "Rhode Island",
      `_STATE` == 45 ~ "South Carolina",
      `_STATE` == 46 ~ "South Dakota",
      `_STATE` == 47 ~ "Tennessee",
      `_STATE` == 48 ~ "Texas",
      `_STATE` == 49 ~ "Utah",
      `_STATE` == 50 ~ "Vermont",
      `_STATE` == 51 ~ "Virginia",
      `_STATE` == 53 ~ "Washington",
      `_STATE` == 54 ~ "West Virginia",
      `_STATE` == 55 ~ "Wisconsin",
      `_STATE` == 56 ~ "Wyoming"
    ),
    post = case_when(
      IYEAR == 2021 | IYEAR == 2022 | (IYEAR == 2023 & IMONTH %in% c("01", "02", "03", "04", "05", "06")) ~ 0,
      IYEAR == 2023 & IMONTH %in% c("07", "08", "09", "10", "11", "12") ~ 1,
      TRUE ~ NA_real_
    ),
    prepost = case_when(
      IYEAR == 2022 & IMONTH %in% c("01", "02", "03", "04", "05", "06", "07", "08", "09") ~ 0,
      (IYEAR == 2022 & IMONTH %in% c("10", "11", "12")) | (IYEAR == 2023 & IMONTH %in% c("01", "02", "03", "04", "05", "06")) ~ 1,
      TRUE ~ NA_real_
    ),
    yearmonth = format(as.Date(paste(IYEAR, IMONTH, IDAY, sep = "-")), "%Y-%m"),
    yearmonth_num = case_when(
      IYEAR == 2021 & IMONTH == "01" ~ 1,
      IYEAR == 2021 & IMONTH == "02" ~ 2,
      IYEAR == 2021 & IMONTH == "03" ~ 3,
      IYEAR == 2021 & IMONTH == "04" ~ 4,
      IYEAR == 2021 & IMONTH == "05" ~ 5,
      IYEAR == 2021 & IMONTH == "06" ~ 6,
      IYEAR == 2021 & IMONTH == "07" ~ 7,
      IYEAR == 2021 & IMONTH == "08" ~ 8,
      IYEAR == 2021 & IMONTH == "09" ~ 9,
      IYEAR == 2021 & IMONTH == "10" ~ 10,
      IYEAR == 2021 & IMONTH == "11" ~ 11,
      IYEAR == 2021 & IMONTH == "12" ~ 12,
      IYEAR == 2022 & IMONTH == "01" ~ 13,
      IYEAR == 2022 & IMONTH == "02" ~ 14,
      IYEAR == 2022 & IMONTH == "03" ~ 15,
      IYEAR == 2022 & IMONTH == "04" ~ 16,
      IYEAR == 2022 & IMONTH == "05" ~ 17,
      IYEAR == 2022 & IMONTH == "06" ~ 18,
      IYEAR == 2022 & IMONTH == "07" ~ 19,
      IYEAR == 2022 & IMONTH == "08" ~ 20,
      IYEAR == 2022 & IMONTH == "09" ~ 21,
      IYEAR == 2022 & IMONTH == "10" ~ 22,
      IYEAR == 2022 & IMONTH == "11" ~ 23,
      IYEAR == 2022 & IMONTH == "12" ~ 24,
      IYEAR == 2023 & IMONTH == "01" ~ 25,
      IYEAR == 2023 & IMONTH == "02" ~ 26,
      IYEAR == 2023 & IMONTH == "03" ~ 27,
      IYEAR == 2023 & IMONTH == "04" ~ 28,
      IYEAR == 2023 & IMONTH == "05" ~ 29,
      IYEAR == 2023 & IMONTH == "06" ~ 30,
      IYEAR == 2023 & IMONTH == "07" ~ 31,
      IYEAR == 2023 & IMONTH == "08" ~ 32,
      IYEAR == 2023 & IMONTH == "09" ~ 33,
      IYEAR == 2023 & IMONTH == "10" ~ 34,
      IYEAR == 2023 & IMONTH == "11" ~ 35,
      IYEAR == 2023 & IMONTH == "12" ~ 36,
      TRUE ~ NA_real_
    ),
    intervention = case_when(
      state == "Georgia" ~ 1, # Georgia
      state == "South Dakota" ~ 0, # Alabama, Florida, Texas, Mississippi
      TRUE ~ NA_real_
    ),
    disability = case_when(BLIND == 1 |
                             DEAF == 1 |
                             DECIDE == 1 |
                             DIFFWALK == 1 |
                             DIFFDRES == 1 |
                             DIFFALON == 1 ~ 1,
                           TRUE ~ NA_real_)
  )
```

# Create survey object
```{r}
# Create survey design object
survey_2123 <- svydesign(id = ~`_PSU`, strata = ~`_STSTR`, weights = ~`_LLCPWT`, data = merge_2123, nest = TRUE)

# Handle single-PSU strata by treating them as adjusted PSU
options(survey.lonely.psu = "adjust")
```

# Select target population
```{r}
eligible <- survey_2123 %>%
  subset(
    state %in% c("Georgia", "South Dakota") &
      `_AGE80` >= 19 & `_AGE80` <= 64 & # 19-64 years old
      fpg <= 100 & # Income up to 100% FPL
      # (PREGNANT != 1 | is.na(PREGNANT)) & # Not pregnant
      # (BLIND != 1 | is.na(BLIND)) & # Not legally blind
      # (DEAF != 1 | is.na(DEAF)) & # Not deaf
      # (DECIDE != 1 | is.na(DECIDE)) & # No difficulty with cognition
      # (DIFFWALK != 1 |
      #    is.na(DIFFWALK)) & # No difficulty with mobility
      # (DIFFDRES != 1 |
      #    is.na(DIFFDRES)) & # No difficulty with self-care
      # (DIFFALON != 1 |
      #    is.na(DIFFALON)) & # No difficulty with independent living
      # (children_clean == 0 | (children_clean >= 1 &
      #    fpg > 30)) & # No parents with income under 30% FPL
      IYEAR %in% c(2021, 2022, 2023) # Date range: 1/1/2022 - 12/31/2023
      # ((IYEAR == 2022 & IMONTH %in% c("07", "08", "09", "10", "11", "12")) | IYEAR == 2023)
  )

eligible_raw <- merge_2123 %>%
  filter(
    state %in% c("Georgia", "South Dakota") &
      `_AGE80` >= 19 & `_AGE80` <= 64 & # 19-64 years old
      fpg <= 100 & # Income up to 100% FPL
      # (PREGNANT != 1 | is.na(PREGNANT)) & # Not pregnant
      # # (BLIND != 1 | is.na(BLIND)) & # Not legally blind
      # (DEAF != 1 | is.na(DEAF)) & # Not deaf
      # (DECIDE != 1 | is.na(DECIDE)) & # No difficulty with cognition
      # (DIFFWALK != 1 |
      #    is.na(DIFFWALK)) & # No difficulty with mobility
      # (DIFFDRES != 1 |
      #    is.na(DIFFDRES)) & # No difficulty with self-care
      # (DIFFALON != 1 |
      #    is.na(DIFFALON)) & # No difficulty with independent living
      # (children_clean == 0 | (children_clean >= 1 &
      #    fpg > 30)) & # No parents with income under 30% FPL
      IYEAR %in% c(2021, 2022, 2023) # Date range: 1/1/2022 - 12/31/2023
      # ((IYEAR == 2022 & IMONTH %in% c("07", "08", "09", "10", "11", "12")) | IYEAR == 2023)
  )
```

# Plot data - months
```{r}
# Medicaid coverage
medicaid_yearmonth <- svytable(~medicaid + yearmonth + intervention, eligible) %>%
  as.data.frame() %>%
  group_by(yearmonth, intervention) %>%
  summarize(
    total = sum(Freq),
    medicaid_1 = sum(Freq[medicaid == 1]),
    percentage = (medicaid_1 / total) * 100
  ) %>%
  ungroup()

medicaid_yearmonth_plot <- ggplot(medicaid_yearmonth, aes(x = yearmonth, y = percentage, color = intervention, group = intervention)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Has Medicaid",
    x = "yearmonth",
    y = "Percentage",
    color = ""
  ) +
  # scale_x_discrete(labels = c("2022 Q1", "2022 Q2", "2022 Q3", "2022 Q4", "2023 Q1", "2023 Q2", "2023 Q3", "2023 Q4")) +
  scale_color_discrete(labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

medicaid_yearmonth_plot
#ggsave("medicaid_yearmonth_plot.jpg")

# ESI
esi_yearmonth <- svytable(~esi + yearmonth + intervention, eligible) %>%
  as.data.frame() %>%
  group_by(yearmonth, intervention) %>%
  summarize(
    total = sum(Freq),
    esi_1 = sum(Freq[esi == 1]),
    percentage = (esi_1 / total) * 100
  ) %>%
  ungroup()

esi_yearmonth_plot <- ggplot(esi_yearmonth, aes(x = yearmonth, y = percentage, color = intervention, group = intervention)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Has employer-sponsored insurance",
    x = "yearmonth",
    y = "Percentage",
    color = ""
  ) +
  # scale_x_discrete(labels = c("2022 Q1", "2022 Q2", "2022 Q3", "2022 Q4", "2023 Q1", "2023 Q2", "2023 Q3", "2023 Q4")) +
  scale_color_discrete(labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

esi_yearmonth_plot
#ggsave("esi_yearmonth_plot.jpg")

# Uninsured
uninsured_yearmonth <- svytable(~uninsured + yearmonth + intervention, eligible) %>%
  as.data.frame() %>%
  group_by(yearmonth, intervention) %>%
  summarize(
    total = sum(Freq),
    uninsured_1 = sum(Freq[uninsured == 1]),
    percentage = (uninsured_1 / total) * 100
  ) %>%
  ungroup()

uninsured_yearmonth_plot <- ggplot(uninsured_yearmonth, aes(x = yearmonth, y = percentage, color = intervention, group = intervention)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Uninsured",
    x = "yearmonth",
    y = "Percentage",
    color = ""
  ) +
  # scale_x_discrete(labels = c("2022 Q1", "2022 Q2", "2022 Q3", "2022 Q4", "2023 Q1", "2023 Q2", "2023 Q3", "2023 Q4")) +
  scale_color_discrete(labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

uninsured_yearmonth_plot
#ggsave("uninsured_yearmonth_plot.jpg")

# Qualifying activities
qualifying_yearmonth <- svytable(~qualifying + yearmonth + intervention, eligible) %>%
  as.data.frame() %>%
  group_by(yearmonth, intervention) %>%
  summarize(
    total = sum(Freq),
    qualifying_1 = sum(Freq[qualifying == 1]),
    percentage = (qualifying_1 / total) * 100
  ) %>%
  ungroup()

qualifying_yearmonth_plot <- ggplot(qualifying_yearmonth, aes(x = yearmonth, y = percentage, color = intervention, group = intervention)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Qualifying activities",
    x = "yearmonth",
    y = "Percentage",
    color = ""
  ) +
  # scale_x_discrete(labels = c("2022 Q1", "2022 Q2", "2022 Q3", "2022 Q4", "2023 Q1", "2023 Q2", "2023 Q3", "2023 Q4")) +
  scale_color_discrete(labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

qualifying_yearmonth_plot
#ggsave("qualifying_yearmonth_plot.jpg")

# Employed
employed_yearmonth <- svytable(~employed + yearmonth + intervention, eligible) %>%
  as.data.frame() %>%
  group_by(yearmonth, intervention) %>%
  summarize(
    total = sum(Freq),
    employed_1 = sum(Freq[employed == 1]),
    percentage = (employed_1 / total) * 100
  ) %>%
  ungroup()

employed_yearmonth_plot <- ggplot(employed_yearmonth, aes(x = yearmonth, y = percentage, color = intervention, group = intervention)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Employed",
    x = "yearmonth",
    y = "Percentage",
    color = ""
  ) +
  # scale_x_discrete(labels = c("2022 Q1", "2022 Q2", "2022 Q3", "2022 Q4", "2023 Q1", "2023 Q2", "2023 Q3", "2023 Q4")) +
  scale_color_discrete(labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

employed_yearmonth_plot
#ggsave("employed_yearmonth_plot.jpg")

# Student
student_yearmonth <- svytable(~student + yearmonth + intervention, eligible) %>%
  as.data.frame() %>%
  group_by(yearmonth, intervention) %>%
  summarize(
    total = sum(Freq),
    student_1 = sum(Freq[student == 1]),
    percentage = (student_1 / total) * 100
  ) %>%
  ungroup()

student_yearmonth_plot <- ggplot(student_yearmonth, aes(x = yearmonth, y = percentage, color = intervention, group = intervention)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Student",
    x = "yearmonth",
    y = "Percentage",
    color = ""
  ) +
  # scale_x_discrete(labels = c("2022 Q1", "2022 Q2", "2022 Q3", "2022 Q4", "2023 Q1", "2023 Q2", "2023 Q3", "2023 Q4")) +
  scale_color_discrete(labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

student_yearmonth_plot
#ggsave("student_yearmonth_plot.jpg")

# PCP
pcp_yearmonth <- svytable(~pcp + yearmonth + intervention, eligible) %>%
  as.data.frame() %>%
  group_by(yearmonth, intervention) %>%
  summarize(
    total = sum(Freq),
    pcp_1 = sum(Freq[pcp == 1]),
    percentage = (pcp_1 / total) * 100
  ) %>%
  ungroup()

pcp_yearmonth_plot <- ggplot(pcp_yearmonth, aes(x = yearmonth, y = percentage, color = intervention, group = intervention)) +
  geom_line() +
  geom_point() +
  labs(
    title = "PCP",
    x = "yearmonth",
    y = "Percentage",
    color = ""
  ) +
  # scale_x_discrete(labels = c("2022 Q1", "2022 Q2", "2022 Q3", "2022 Q4", "2023 Q1", "2023 Q2", "2023 Q3", "2023 Q4")) +
  scale_color_discrete(labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

pcp_yearmonth_plot
#ggsave("pcp_yearmonth_plot.jpg")

# Could not afford to see doctor in past 12 months
not_afford_yearmonth <- svytable(~not_afford + yearmonth + intervention, eligible) %>%
  as.data.frame() %>%
  group_by(yearmonth, intervention) %>%
  summarize(
    total = sum(Freq),
    not_afford_1 = sum(Freq[not_afford == 1]),
    percentage = (not_afford_1 / total) * 100
  ) %>%
  ungroup()

not_afford_yearmonth_plot <- ggplot(not_afford_yearmonth, aes(x = yearmonth, y = percentage, color = intervention, group = intervention)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Could not afford to see doctor in past 12 months",
    x = "yearmonth",
    y = "Percentage",
    color = ""
  ) +
  # scale_x_discrete(labels = c("2022 Q1", "2022 Q2", "2022 Q3", "2022 Q4", "2023 Q1", "2023 Q2", "2023 Q3", "2023 Q4")) +
  scale_color_discrete(labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

not_afford_yearmonth_plot
#ggsave("not_afford_yearmonth_plot.jpg")

# Unemployed
unemployed_yearmonth <- svytable(~unemployed + yearmonth + intervention, eligible) %>%
  as.data.frame() %>%
  group_by(yearmonth, intervention) %>%
  summarize(
    total = sum(Freq),
    unemployed_1 = sum(Freq[unemployed == 1]),
    percentage = (unemployed_1 / total) * 100
  ) %>%
  ungroup()

unemployed_yearmonth_plot <- ggplot(unemployed_yearmonth, aes(x = yearmonth, y = percentage, color = intervention, group = intervention)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Unemployed",
    x = "yearmonth",
    y = "Percentage",
    color = ""
  ) +
  # scale_x_discrete(labels = c("2022 Q1", "2022 Q2", "2022 Q3", "2022 Q4", "2023 Q1", "2023 Q2", "2023 Q3", "2023 Q4")) +
  scale_color_discrete(labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

unemployed_yearmonth_plot
#ggsave("unemployed_yearmonth_plot.jpg")
```

# Plot data - quarters
```{r}
# Medicaid coverage
medicaid_quarter <- svytable(~medicaid + quarter + intervention, eligible) %>%
  as.data.frame() %>%
  group_by(quarter, intervention) %>%
  summarize(
    total = sum(Freq),
    medicaid_1 = sum(Freq[medicaid == 1]),
    percentage = (medicaid_1 / total) * 100
  ) %>%
  ungroup()

medicaid_quarter_plot <- ggplot(medicaid_quarter, aes(x = quarter, y = percentage, color = intervention, group = intervention)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Has Medicaid",
    x = "Quarter",
    y = "Percentage",
    color = ""
  ) +
  # scale_x_discrete(labels = c("2022 Q1", "2022 Q2", "2022 Q3", "2022 Q4", "2023 Q1", "2023 Q2", "2023 Q3", "2023 Q4")) +
  scale_color_discrete(labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

medicaid_quarter_plot
#ggsave("medicaid_quarter_plot.jpg")

# ESI
esi_quarter <- svytable(~esi + quarter + intervention, eligible) %>%
  as.data.frame() %>%
  group_by(quarter, intervention) %>%
  summarize(
    total = sum(Freq),
    esi_1 = sum(Freq[esi == 1]),
    percentage = (esi_1 / total) * 100
  ) %>%
  ungroup()

esi_quarter_plot <- ggplot(esi_quarter, aes(x = quarter, y = percentage, color = intervention, group = intervention)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Has employer-sponsored insurance",
    x = "Quarter",
    y = "Percentage",
    color = ""
  ) +
  # scale_x_discrete(labels = c("2022 Q1", "2022 Q2", "2022 Q3", "2022 Q4", "2023 Q1", "2023 Q2", "2023 Q3", "2023 Q4")) +
  scale_color_discrete(labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

esi_quarter_plot
#ggsave("esi_quarter_plot.jpg")

# Uninsured
uninsured_quarter <- svytable(~uninsured + quarter + intervention, eligible) %>%
  as.data.frame() %>%
  group_by(quarter, intervention) %>%
  summarize(
    total = sum(Freq),
    uninsured_1 = sum(Freq[uninsured == 1]),
    percentage = (uninsured_1 / total) * 100
  ) %>%
  ungroup()

uninsured_quarter_plot <- ggplot(uninsured_quarter, aes(x = quarter, y = percentage, color = intervention, group = intervention)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Uninsured",
    x = "Quarter",
    y = "Percentage",
    color = ""
  ) +
  # scale_x_discrete(labels = c("2022 Q1", "2022 Q2", "2022 Q3", "2022 Q4", "2023 Q1", "2023 Q2", "2023 Q3", "2023 Q4")) +
  scale_color_discrete(labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

uninsured_quarter_plot
#ggsave("uninsured_quarter_plot.jpg")

# Qualifying activities
qualifying_quarter <- svytable(~qualifying + quarter + intervention, eligible) %>%
  as.data.frame() %>%
  group_by(quarter, intervention) %>%
  summarize(
    total = sum(Freq),
    qualifying_1 = sum(Freq[qualifying == 1]),
    percentage = (qualifying_1 / total) * 100
  ) %>%
  ungroup()

qualifying_quarter_plot <- ggplot(qualifying_quarter, aes(x = quarter, y = percentage, color = intervention, group = intervention)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Qualifying activities",
    x = "Quarter",
    y = "Percentage",
    color = ""
  ) +
  # scale_x_discrete(labels = c("2022 Q1", "2022 Q2", "2022 Q3", "2022 Q4", "2023 Q1", "2023 Q2", "2023 Q3", "2023 Q4")) +
  scale_color_discrete(labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

qualifying_quarter_plot
#ggsave("qualifying_quarter_plot.jpg")

# Employed
employed_quarter <- svytable(~employed + quarter + intervention, eligible) %>%
  as.data.frame() %>%
  group_by(quarter, intervention) %>%
  summarize(
    total = sum(Freq),
    employed_1 = sum(Freq[employed == 1]),
    percentage = (employed_1 / total) * 100
  ) %>%
  ungroup()

employed_quarter_plot <- ggplot(employed_quarter, aes(x = quarter, y = percentage, color = intervention, group = intervention)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Employed",
    x = "Quarter",
    y = "Percentage",
    color = ""
  ) +
  # scale_x_discrete(labels = c("2022 Q1", "2022 Q2", "2022 Q3", "2022 Q4", "2023 Q1", "2023 Q2", "2023 Q3", "2023 Q4")) +
  scale_color_discrete(labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

employed_quarter_plot
#ggsave("employed_quarter_plot.jpg")

# Student
student_quarter <- svytable(~student + quarter + intervention, eligible) %>%
  as.data.frame() %>%
  group_by(quarter, intervention) %>%
  summarize(
    total = sum(Freq),
    student_1 = sum(Freq[student == 1]),
    percentage = (student_1 / total) * 100
  ) %>%
  ungroup()

student_quarter_plot <- ggplot(student_quarter, aes(x = quarter, y = percentage, color = intervention, group = intervention)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Student",
    x = "Quarter",
    y = "Percentage",
    color = ""
  ) +
  # scale_x_discrete(labels = c("2022 Q1", "2022 Q2", "2022 Q3", "2022 Q4", "2023 Q1", "2023 Q2", "2023 Q3", "2023 Q4")) +
  scale_color_discrete(labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

student_quarter_plot
#ggsave("student_quarter_plot.jpg")

# PCP
pcp_quarter <- svytable(~pcp + quarter + intervention, eligible) %>%
  as.data.frame() %>%
  group_by(quarter, intervention) %>%
  summarize(
    total = sum(Freq),
    pcp_1 = sum(Freq[pcp == 1]),
    percentage = (pcp_1 / total) * 100
  ) %>%
  ungroup()

pcp_quarter_plot <- ggplot(pcp_quarter, aes(x = quarter, y = percentage, color = intervention, group = intervention)) +
  geom_line() +
  geom_point() +
  labs(
    title = "PCP",
    x = "Quarter",
    y = "Percentage",
    color = ""
  ) +
  # scale_x_discrete(labels = c("2022 Q1", "2022 Q2", "2022 Q3", "2022 Q4", "2023 Q1", "2023 Q2", "2023 Q3", "2023 Q4")) +
  scale_color_discrete(labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

pcp_quarter_plot
#ggsave("pcp_quarter_plot.jpg")

# Could not afford to see doctor in past 12 months
not_afford_quarter <- svytable(~not_afford + quarter + intervention, eligible) %>%
  as.data.frame() %>%
  group_by(quarter, intervention) %>%
  summarize(
    total = sum(Freq),
    not_afford_1 = sum(Freq[not_afford == 1]),
    percentage = (not_afford_1 / total) * 100
  ) %>%
  ungroup()

not_afford_quarter_plot <- ggplot(not_afford_quarter, aes(x = quarter, y = percentage, color = intervention, group = intervention)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Could not afford to see doctor in past 12 months",
    x = "Quarter",
    y = "Percentage",
    color = ""
  ) +
  # scale_x_discrete(labels = c("2022 Q1", "2022 Q2", "2022 Q3", "2022 Q4", "2023 Q1", "2023 Q2", "2023 Q3", "2023 Q4")) +
  scale_color_discrete(labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

not_afford_quarter_plot
#ggsave("not_afford_quarter_plot.jpg")

# Unemployed
unemployed_quarter <- svytable(~unemployed + quarter + intervention, eligible) %>%
  as.data.frame() %>%
  group_by(quarter, intervention) %>%
  summarize(
    total = sum(Freq),
    unemployed_1 = sum(Freq[unemployed == 1]),
    percentage = (unemployed_1 / total) * 100
  ) %>%
  ungroup()

unemployed_quarter_plot <- ggplot(unemployed_quarter, aes(x = quarter, y = percentage, color = intervention, group = intervention)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Unemployed",
    x = "Quarter",
    y = "Percentage",
    color = ""
  ) +
  # scale_x_discrete(labels = c("2022 Q1", "2022 Q2", "2022 Q3", "2022 Q4", "2023 Q1", "2023 Q2", "2023 Q3", "2023 Q4")) +
  scale_color_discrete(labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

unemployed_quarter_plot
#ggsave("unemployed_quarter_plot.jpg")
```

# Plot data - halves
```{r}
# Medicaid coverage
medicaid_half <- svytable(~medicaid + half + intervention, eligible) %>%
  as.data.frame() %>%
  group_by(half, intervention) %>%
  summarize(
    total = sum(Freq),
    medicaid_1 = sum(Freq[medicaid == 1]),
    percentage = (medicaid_1 / total) * 100
  ) %>%
  ungroup()

medicaid_half_plot <- ggplot(medicaid_half, aes(x = half, y = percentage, color = intervention, group = intervention)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Has Medicaid",
    x = "Half",
    y = "Percentage",
    color = ""
  ) +
  # scale_x_discrete(labels = c("2022 Jan-June", "2022 July-Dec", "2023 Jan-June", "2023 July-Dec")) +
  scale_color_discrete(labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

medicaid_half_plot
#ggsave("medicaid_half_plot.jpg")

# ESI
esi_half <- svytable(~esi + half + intervention, eligible) %>%
  as.data.frame() %>%
  group_by(half, intervention) %>%
  summarize(
    total = sum(Freq),
    esi_1 = sum(Freq[esi == 1]),
    percentage = (esi_1 / total) * 100
  ) %>%
  ungroup()

esi_half_plot <- ggplot(esi_half, aes(x = half, y = percentage, color = intervention, group = intervention)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Has ESI",
    x = "Half",
    y = "Percentage",
    color = ""
  ) +
  # scale_x_discrete(labels = c("2022 Jan-June", "2022 July-Dec", "2023 Jan-June", "2023 July-Dec")) +
  scale_color_discrete(labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

esi_half_plot
#ggsave("esi_half_plot.jpg")

# Uninsured
uninsured_half <- svytable(~uninsured + half + intervention, eligible) %>%
  as.data.frame() %>%
  group_by(half, intervention) %>%
  summarize(
    total = sum(Freq),
    uninsured_1 = sum(Freq[uninsured == 1]),
    percentage = (uninsured_1 / total) * 100
  ) %>%
  ungroup()

uninsured_half_plot <- ggplot(uninsured_half, aes(x = half, y = percentage, color = intervention, group = intervention)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Uninsured",
    x = "Half",
    y = "Percentage",
    color = ""
  ) +
  # scale_x_discrete(labels = c("2022 Jan-June", "2022 July-Dec", "2023 Jan-June", "2023 July-Dec")) +
  scale_color_discrete(labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

uninsured_half_plot
#ggsave("uninsured_half_plot.jpg")

# Qualifying activities
qualifying_half <- svytable(~qualifying + half + intervention, eligible) %>%
  as.data.frame() %>%
  group_by(half, intervention) %>%
  summarize(
    total = sum(Freq),
    qualifying_1 = sum(Freq[qualifying == 1]),
    percentage = (qualifying_1 / total) * 100
  ) %>%
  ungroup()

qualifying_half_plot <- ggplot(qualifying_half, aes(x = half, y = percentage, color = intervention, group = intervention)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Qualifying activities",
    x = "Half",
    y = "Percentage",
    color = ""
  ) +
  # scale_x_discrete(labels = c("2022 Jan-June", "2022 July-Dec", "2023 Jan-June", "2023 July-Dec")) +
  scale_color_discrete(labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

qualifying_half_plot
#ggsave("qualifying_half_plot.jpg")

# Employed
employed_half <- svytable(~employed + half + intervention, eligible) %>%
  as.data.frame() %>%
  group_by(half, intervention) %>%
  summarize(
    total = sum(Freq),
    employed_1 = sum(Freq[employed == 1]),
    percentage = (employed_1 / total) * 100
  ) %>%
  ungroup()

employed_half_plot <- ggplot(employed_half, aes(x = half, y = percentage, color = intervention, group = intervention)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Employed",
    x = "Half",
    y = "Percentage",
    color = ""
  ) +
  # scale_x_discrete(labels = c("2022 Jan-June", "2022 July-Dec", "2023 Jan-June", "2023 July-Dec")) +
  scale_color_discrete(labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

employed_half_plot
#ggsave("employed_half_plot.jpg")

# Student
student_half <- svytable(~student + half + intervention, eligible) %>%
  as.data.frame() %>%
  group_by(half, intervention) %>%
  summarize(
    total = sum(Freq),
    student_1 = sum(Freq[student == 1]),
    percentage = (student_1 / total) * 100
  ) %>%
  ungroup()

student_half_plot <- ggplot(student_half, aes(x = half, y = percentage, color = intervention, group = intervention)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Student",
    x = "Half",
    y = "Percentage",
    color = ""
  ) +
  # scale_x_discrete(labels = c("2022 Jan-June", "2022 July-Dec", "2023 Jan-June", "2023 July-Dec")) +
  scale_color_discrete(labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

student_half_plot
#ggsave("student_half_plot.jpg")

# PCP
pcp_half <- svytable(~pcp + half + intervention, eligible) %>%
  as.data.frame() %>%
  group_by(half, intervention) %>%
  summarize(
    total = sum(Freq),
    pcp_1 = sum(Freq[pcp == 1]),
    percentage = (pcp_1 / total) * 100
  ) %>%
  ungroup()

pcp_half_plot <- ggplot(pcp_half, aes(x = half, y = percentage, color = intervention, group = intervention)) +
  geom_line() +
  geom_point() +
  labs(
    title = "PCP",
    x = "Half",
    y = "Percentage",
    color = ""
  ) +
  # scale_x_discrete(labels = c("2022 Jan-June", "2022 July-Dec", "2023 Jan-June", "2023 July-Dec")) +
  scale_color_discrete(labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

pcp_half_plot
#ggsave("pcp_half_plot.jpg")

# Could not afford to see doctor in past 12 months
not_afford_half <- svytable(~not_afford + half + intervention, eligible) %>%
  as.data.frame() %>%
  group_by(half, intervention) %>%
  summarize(
    total = sum(Freq),
    not_afford_1 = sum(Freq[not_afford == 1]),
    percentage = (not_afford_1 / total) * 100
  ) %>%
  ungroup()

not_afford_half_plot <- ggplot(not_afford_half, aes(x = half, y = percentage, color = intervention, group = intervention)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Could not afford to see doctor in past 12 months",
    x = "Half",
    y = "Percentage",
    color = ""
  ) +
  # scale_x_discrete(labels = c("2022 Jan-June", "2022 July-Dec", "2023 Jan-June", "2023 July-Dec")) +
  scale_color_discrete(labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

not_afford_half_plot
#ggsave("not_afford_half_plot.jpg")

# Unemployed
unemployed_half <- svytable(~unemployed + half + intervention, eligible) %>%
  as.data.frame() %>%
  group_by(half, intervention) %>%
  summarize(
    total = sum(Freq),
    unemployed_1 = sum(Freq[unemployed == 1]),
    percentage = (unemployed_1 / total) * 100
  ) %>%
  ungroup()

unemployed_half_plot <- ggplot(unemployed_half, aes(x = half, y = percentage, color = intervention, group = intervention)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Unemployed",
    x = "Half",
    y = "Percentage",
    color = ""
  ) +
  # scale_x_discrete(labels = c("2022 Jan-June", "2022 July-Dec", "2023 Jan-June", "2023 July-Dec")) +
  scale_color_discrete(labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

unemployed_half_plot
#ggsave("unemployed_half_plot.jpg")
```

# Plot data - years
```{r}
# Medicaid coverage
medicaid_IYEAR <- svytable(~medicaid + IYEAR + intervention, eligible) %>%
  as.data.frame() %>%
  group_by(IYEAR, intervention) %>%
  summarize(
    total = sum(Freq),
    medicaid_1 = sum(Freq[medicaid == 1]),
    percentage = (medicaid_1 / total) * 100
  ) %>%
  ungroup()

medicaid_IYEAR_plot <- ggplot(medicaid_IYEAR, aes(x = IYEAR, y = percentage, color = intervention, group = intervention)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Has Medicaid",
    x = "IYEAR",
    y = "Percentage",
    color = ""
  ) +
  # scale_x_discrete(labels = c("2022 Jan-June", "2022 July-Dec", "2023 Jan-June", "2023 July-Dec")) +
  scale_color_discrete(labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

medicaid_IYEAR_plot
#ggsave("medicaid_IYEAR_plot.jpg")

# ESI
esi_IYEAR <- svytable(~esi + IYEAR + intervention, eligible) %>%
  as.data.frame() %>%
  group_by(IYEAR, intervention) %>%
  summarize(
    total = sum(Freq),
    esi_1 = sum(Freq[esi == 1]),
    percentage = (esi_1 / total) * 100
  ) %>%
  ungroup()

esi_IYEAR_plot <- ggplot(esi_IYEAR, aes(x = IYEAR, y = percentage, color = intervention, group = intervention)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Has ESI",
    x = "IYEAR",
    y = "Percentage",
    color = ""
  ) +
  # scale_x_discrete(labels = c("2022 Jan-June", "2022 July-Dec", "2023 Jan-June", "2023 July-Dec")) +
  scale_color_discrete(labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

esi_IYEAR_plot
#ggsave("esi_IYEAR_plot.jpg")

# Uninsured
uninsured_IYEAR <- svytable(~uninsured + IYEAR + intervention, eligible) %>%
  as.data.frame() %>%
  group_by(IYEAR, intervention) %>%
  summarize(
    total = sum(Freq),
    uninsured_1 = sum(Freq[uninsured == 1]),
    percentage = (uninsured_1 / total) * 100
  ) %>%
  ungroup()

uninsured_IYEAR_plot <- ggplot(uninsured_IYEAR, aes(x = IYEAR, y = percentage, color = intervention, group = intervention)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Uninsured",
    x = "IYEAR",
    y = "Percentage",
    color = ""
  ) +
  # scale_x_discrete(labels = c("2022 Jan-June", "2022 July-Dec", "2023 Jan-June", "2023 July-Dec")) +
  scale_color_discrete(labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

uninsured_IYEAR_plot
#ggsave("uninsured_IYEAR_plot.jpg")

# Qualifying activities
qualifying_IYEAR <- svytable(~qualifying + IYEAR + intervention, eligible) %>%
  as.data.frame() %>%
  group_by(IYEAR, intervention) %>%
  summarize(
    total = sum(Freq),
    qualifying_1 = sum(Freq[qualifying == 1]),
    percentage = (qualifying_1 / total) * 100
  ) %>%
  ungroup()

qualifying_IYEAR_plot <- ggplot(qualifying_IYEAR, aes(x = IYEAR, y = percentage, color = intervention, group = intervention)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Qualifying activities",
    x = "IYEAR",
    y = "Percentage",
    color = ""
  ) +
  # scale_x_discrete(labels = c("2022 Jan-June", "2022 July-Dec", "2023 Jan-June", "2023 July-Dec")) +
  scale_color_discrete(labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

qualifying_IYEAR_plot
#ggsave("qualifying_IYEAR_plot.jpg")

# Employed
employed_IYEAR <- svytable(~employed + IYEAR + intervention, eligible) %>%
  as.data.frame() %>%
  group_by(IYEAR, intervention) %>%
  summarize(
    total = sum(Freq),
    employed_1 = sum(Freq[employed == 1]),
    percentage = (employed_1 / total) * 100
  ) %>%
  ungroup()

employed_IYEAR_plot <- ggplot(employed_IYEAR, aes(x = IYEAR, y = percentage, color = intervention, group = intervention)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Employed",
    x = "IYEAR",
    y = "Percentage",
    color = ""
  ) +
  # scale_x_discrete(labels = c("2022 Jan-June", "2022 July-Dec", "2023 Jan-June", "2023 July-Dec")) +
  scale_color_discrete(labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

employed_IYEAR_plot
#ggsave("employed_IYEAR_plot.jpg")

# Student
student_IYEAR <- svytable(~student + IYEAR + intervention, eligible) %>%
  as.data.frame() %>%
  group_by(IYEAR, intervention) %>%
  summarize(
    total = sum(Freq),
    student_1 = sum(Freq[student == 1]),
    percentage = (student_1 / total) * 100
  ) %>%
  ungroup()

student_IYEAR_plot <- ggplot(student_IYEAR, aes(x = IYEAR, y = percentage, color = intervention, group = intervention)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Student",
    x = "IYEAR",
    y = "Percentage",
    color = ""
  ) +
  # scale_x_discrete(labels = c("2022 Jan-June", "2022 July-Dec", "2023 Jan-June", "2023 July-Dec")) +
  scale_color_discrete(labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

student_IYEAR_plot
#ggsave("student_IYEAR_plot.jpg")

# PCP
pcp_IYEAR <- svytable(~pcp + IYEAR + intervention, eligible) %>%
  as.data.frame() %>%
  group_by(IYEAR, intervention) %>%
  summarize(
    total = sum(Freq),
    pcp_1 = sum(Freq[pcp == 1]),
    percentage = (pcp_1 / total) * 100
  ) %>%
  ungroup()

pcp_IYEAR_plot <- ggplot(pcp_IYEAR, aes(x = IYEAR, y = percentage, color = intervention, group = intervention)) +
  geom_line() +
  geom_point() +
  labs(
    title = "PCP",
    x = "IYEAR",
    y = "Percentage",
    color = ""
  ) +
  # scale_x_discrete(labels = c("2022 Jan-June", "2022 July-Dec", "2023 Jan-June", "2023 July-Dec")) +
  scale_color_discrete(labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

pcp_IYEAR_plot
#ggsave("pcp_IYEAR_plot.jpg")

# Could not afford to see doctor in past 12 months
not_afford_IYEAR <- svytable(~not_afford + IYEAR + intervention, eligible) %>%
  as.data.frame() %>%
  group_by(IYEAR, intervention) %>%
  summarize(
    total = sum(Freq),
    not_afford_1 = sum(Freq[not_afford == 1]),
    percentage = (not_afford_1 / total) * 100
  ) %>%
  ungroup()

not_afford_IYEAR_plot <- ggplot(not_afford_IYEAR, aes(x = IYEAR, y = percentage, color = intervention, group = intervention)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Could not afford to see doctor in past 12 months",
    x = "IYEAR",
    y = "Percentage",
    color = ""
  ) +
  # scale_x_discrete(labels = c("2022 Jan-June", "2022 July-Dec", "2023 Jan-June", "2023 July-Dec")) +
  scale_color_discrete(labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

not_afford_IYEAR_plot
#ggsave("not_afford_IYEAR_plot.jpg")

# Unemployed
unemployed_IYEAR <- svytable(~unemployed + IYEAR + intervention, eligible) %>%
  as.data.frame() %>%
  group_by(IYEAR, intervention) %>%
  summarize(
    total = sum(Freq),
    unemployed_1 = sum(Freq[unemployed == 1]),
    percentage = (unemployed_1 / total) * 100
  ) %>%
  ungroup()

unemployed_IYEAR_plot <- ggplot(unemployed_IYEAR, aes(x = IYEAR, y = percentage, color = intervention, group = intervention)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Unemployed",
    x = "IYEAR",
    y = "Percentage",
    color = ""
  ) +
  # scale_x_discrete(labels = c("2022 Jan-June", "2022 July-Dec", "2023 Jan-June", "2023 July-Dec")) +
  scale_color_discrete(labels = c("South Dakota", "Georgia")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

unemployed_IYEAR_plot
#ggsave("unemployed_IYEAR_plot.jpg")
```

# Test parallel trends
```{r}
# Subset to pre-period
eligible_pre <- eligible %>% subset(post == 0)

# Medicaid
medicaid_unadj_pttest <- svyglm(medicaid ~ intervention * yearmonth_num, design = eligible_pre)
summary(medicaid_unadj_pttest)

# Uninsured
uninsured_unadj_pttest <- svyglm(uninsured ~ intervention * yearmonth_num, design = eligible_pre)
summary(uninsured_unadj_pttest)

# Qualifying activities
qualifying_unadj_pttest <- svyglm(qualifying ~ intervention * yearmonth_num, design = eligible_pre)
summary(qualifying_unadj_pttest)

# Employed
employed_unadj_pttest <- svyglm(employed ~ intervention * yearmonth_num, design = eligible_pre)
summary(employed_unadj_pttest)

# Student
student_unadj_pttest <- svyglm(student ~ intervention * yearmonth_num, design = eligible_pre)
summary(student_unadj_pttest)

# Employer-sponsored insurance
esi_unadj_pttest <- svyglm(esi ~ intervention * yearmonth_num, design = eligible_pre)
summary(esi_unadj_pttest)

# Access to PCP
pcp_unadj_pttest <- svyglm(pcp ~ intervention * yearmonth_num, design = eligible_pre)
summary(pcp_unadj_pttest)

# Cost-related delays in care
not_afford_unadj_pttest <- svyglm(not_afford ~ intervention * yearmonth_num, design = eligible_pre)
summary(not_afford_unadj_pttest)
```

# Unadjusted DID analysis
```{r}
# Medicaid
medicaid_unadj <- svyglm(medicaid ~ intervention * post, design = eligible)
summary(medicaid_unadj)

# Uninsured
uninsured_unadj <- svyglm(uninsured ~ intervention * post, design = eligible)
summary(uninsured_unadj)

# Qualifying activities
qualifying_unadj <- svyglm(qualifying ~ intervention * post, design = eligible)
summary(qualifying_unadj)

# Employed
employed_unadj <- svyglm(employed ~ intervention * post, design = eligible)
summary(employed_unadj)

# Student
student_unadj <- svyglm(student ~ intervention * post, design = eligible)
summary(student_unadj)

# Employer-sponsored insurance
esi_unadj <- svyglm(esi ~ intervention * post, design = eligible)
summary(esi_unadj)

# Access to PCP
pcp_unadj <- svyglm(pcp ~ intervention * post, design = eligible)
summary(pcp_unadj)

# Cost-related delays in care
not_afford_unadj <- svyglm(not_afford ~ intervention * post, design = eligible)
summary(not_afford_unadj)
```

# Adjusted DID analysis
```{r}
# Medicaid
medicaid_adj <- svyglm(medicaid ~ intervention * post + age_cat + sex_cat + race_cat, design = eligible)
summary(medicaid_adj)

# Uninsured
uninsured_adj <- svyglm(uninsured ~ intervention * post + age_cat + sex_cat + race_cat, design = eligible)
summary(uninsured_adj)

# Qualifying activities
qualifying_adj <- svyglm(qualifying ~ intervention * post + age_cat + sex_cat + race_cat, design = eligible)
summary(qualifying_adj)

# Employed
employed_adj <- svyglm(employed ~ intervention * post + age_cat + sex_cat + race_cat, design = eligible)
summary(employed_adj)

# Student
student_adj <- svyglm(student ~ intervention * post + age_cat + sex_cat + race_cat, design = eligible)
summary(student_adj)

# Employer-sponsored insurance
esi_adj <- svyglm(esi ~ intervention * post + age_cat + sex_cat + race_cat, design = eligible)
summary(esi_adj)

# Access to PCP
pcp_adj <- svyglm(pcp ~ intervention * post + age_cat + sex_cat + race_cat, design = eligible)
summary(pcp_adj)

# Cost-related delays in care
not_afford_adj <- svyglm(not_afford ~ intervention * post + age_cat + sex_cat + race_cat, design = eligible)
summary(not_afford_adj)
```